export interface ScopeQuestion {
  question_type: string;
  cross_scope: boolean;
  question: string;
  options: { A: string; B: string; C: string; D: string };
  correct: "A" | "B" | "C" | "D";
  rationale_correct: string;
  rationale_A: string;
  rationale_B: string;
  rationale_C: string;
  rationale_D: string;
}

export type StepQuestions = {
  "EMT-B": ScopeQuestion[];
  "AEMT": ScopeQuestion[];
  "Paramedic": ScopeQuestion[];
};

// ─── DROWNING ────────────────────────────────────────────────────────────────

export const DROWNING_QUESTIONS: Record<number, StepQuestions> = {
  1: {
    "EMT-B": [
      {
        question_type: "Scene Safety",
        cross_scope: true,
        question: "You arrive at the pool. The deck is wet and a crowd has gathered. What is your FIRST priority?",
        options: { A: "Take over CPR from the lifeguard immediately", B: "Don BSI and confirm the scene is safe before approaching", C: "Retrieve the AED from the unit", D: "Interview bystanders about submersion time" },
        correct: "B",
        rationale_correct: "Scene safety and BSI are always first. The wet pool deck is a slip and electrical hazard. Gloves on before patient contact.",
        rationale_A: "Even with CPR in progress, entering an unsafe scene puts you at risk. BSI first.",
        rationale_B: "Correct.",
        rationale_C: "The AED is important but not before confirming scene safety.",
        rationale_D: "History is secondary to establishing it's safe to approach.",
      },
      {
        question_type: "Clinical Decision",
        cross_scope: false,
        question: "You confirm the patient is apneic and pulseless. As an EMT-B, your next step is:",
        options: { A: "Begin high-quality CPR at 30:2 and attach the AED", B: "Suction the airway before starting compressions", C: "Assess pupils and blood glucose", D: "Wait for ALS before initiating treatment" },
        correct: "A",
        rationale_correct: "Cardiac arrest = high-quality CPR + early defibrillation. Start immediately without delay.",
        rationale_A: "Correct.",
        rationale_B: "Suctioning delays compressions. Begin CPR first.",
        rationale_C: "Pupil and glucose checks are not priorities in cardiac arrest.",
        rationale_D: "Never delay BLS waiting for ALS. Begin immediately.",
      },
    ],
    "AEMT": [
      {
        question_type: "Intervention",
        cross_scope: false,
        question: "CPR is ongoing. As an AEMT, which two interventions should you establish concurrently with compressions?",
        options: { A: "BVM ventilations and IV/IO access", B: "OPA insertion and 12-lead ECG", C: "Nasal cannula oxygen and scene documentation", D: "Capnography and spinal immobilization" },
        correct: "A",
        rationale_correct: "BVM at 30:2 and IV/IO access are the AEMT-level priorities alongside CPR. Access allows fluid administration and prepares for ALS medications.",
        rationale_A: "Correct.",
        rationale_B: "OPA is appropriate but 12-lead ECG delays CPR unnecessarily during arrest.",
        rationale_C: "Nasal cannula cannot ventilate an apneic patient. Documentation is never a clinical priority.",
        rationale_D: "Capnography is useful but not a first priority. Spinal immobilization is rarely indicated in drowning.",
      },
      {
        question_type: "Protocol Knowledge",
        cross_scope: false,
        question: "IV access is established. Which medication is within AEMT scope for this cardiac arrest?",
        options: { A: "Epinephrine 1mg IV every 3–5 minutes", B: "Amiodarone 300mg IV push", C: "Normal saline to maintain access — cardiac drugs are Paramedic scope", D: "Adenosine 6mg rapid IV push" },
        correct: "C",
        rationale_correct: "AEMTs establish access and manage fluids. Epinephrine and antiarrhythmics are Paramedic-level in most protocols.",
        rationale_A: "Epinephrine in arrest is Paramedic scope.",
        rationale_B: "Amiodarone is Paramedic-only.",
        rationale_C: "Correct.",
        rationale_D: "Adenosine treats SVT with a pulse, not cardiac arrest, and is Paramedic scope.",
      },
    ],
    "Paramedic": [
      {
        question_type: "Clinical Decision",
        cross_scope: false,
        question: "CPR is ongoing after a 4-minute submersion arrest. After BSI and scene control, your immediate priority as Paramedic is:",
        options: { A: "Analyze rhythm and defibrillate if shockable — don't delay for IV access", B: "Establish IV and give epinephrine 1mg before rhythm analysis", C: "Intubate immediately to secure the airway", D: "Acquire a 12-lead ECG to identify the arrest rhythm" },
        correct: "A",
        rationale_correct: "Rhythm analysis first. Early defibrillation for VF/pVT is the highest-yield intervention. IV and medications follow the first CPR cycle.",
        rationale_A: "Correct.",
        rationale_B: "Epinephrine is given every 3–5 min but rhythm check and possible defibrillation come first.",
        rationale_C: "Intubating before rhythm check delays defibrillation. BVM is acceptable initially.",
        rationale_D: "The monitor/AED pads analyze rhythm; a 12-lead is not the priority tool in arrest.",
      },
      {
        question_type: "Assessment",
        cross_scope: false,
        question: "The monitor shows PEA. In a drowning arrest, which reversible cause should you address first?",
        options: { A: "Hypovolemia", B: "Hypoxia", C: "Hypothermia", D: "Hyperkalemia" },
        correct: "B",
        rationale_correct: "Drowning arrests are asphyxia-driven. Hypoxia is the primary cause — aggressive oxygenation and ventilation are the treatment.",
        rationale_A: "Hypovolemia is possible but not the primary driver in a typical pool submersion.",
        rationale_B: "Correct.",
        rationale_C: "Hypothermia is relevant in prolonged cold-water submersions; 4 minutes in a community pool is unlikely to be the cause.",
        rationale_D: "Hyperkalemia is theoretically possible but not the first H&T to address here.",
      },
    ],
  },
  2: {
    "EMT-B": [
      {
        question_type: "Protocol Knowledge",
        cross_scope: true,
        question: "You take over from the lifeguard. Correct CPR compression rate and depth per AHA guidelines are:",
        options: { A: "100–120/min, at least 2 inches, full chest recoil between compressions", B: "80–100/min, 1–1.5 inches deep", C: "120–140/min, as deep as possible", D: "60–80/min, 2 inches deep" },
        correct: "A",
        rationale_correct: "AHA: 100–120/min, ≥2 inches depth, full recoil. These three elements together define high-quality CPR.",
        rationale_A: "Correct.",
        rationale_B: "Both rate and depth are below guideline minimums.",
        rationale_C: "Above 120/min reduces ventricular filling. Excessive depth causes injury.",
        rationale_D: "60–80/min is too slow.",
      },
      {
        question_type: "Intervention",
        cross_scope: false,
        question: "For ventilation in this apneic arrest you should use:",
        options: { A: "BVM with supplemental O2 at 30:2 ratio", B: "Mouth-to-mask only — BVM requires two providers", C: "High-flow NRB mask at 15 LPM", D: "Nasal cannula at 6 LPM" },
        correct: "A",
        rationale_correct: "BVM with 100% O2 at 30:2 is the BLS standard for apneic cardiac arrest patients.",
        rationale_A: "Correct.",
        rationale_B: "BVM works with one provider using the E-C clamp. Mouth-to-mask is a backup, not preferred.",
        rationale_C: "NRB is for spontaneously breathing patients only.",
        rationale_D: "Nasal cannula cannot provide ventilations.",
      },
    ],
    "AEMT": [
      {
        question_type: "Intervention",
        cross_scope: false,
        question: "As AEMT, what airway upgrade is within your scope for this pulseless apneic patient?",
        options: { A: "Supraglottic airway (King LT or LMA)", B: "Endotracheal intubation with RSI medications", C: "Surgical cricothyrotomy as primary airway", D: "Blind nasotracheal intubation" },
        correct: "A",
        rationale_correct: "AEMTs are trained in supraglottic airway devices. This is the appropriate upgrade from BVM for a pulseless patient in AEMT scope.",
        rationale_A: "Correct.",
        rationale_B: "RSI with paralytic agents is Paramedic scope.",
        rationale_C: "Surgical airway is a rescue intervention, not primary.",
        rationale_D: "Blind NTI is not a standard AEMT skill.",
      },
      {
        question_type: "Clinical Decision",
        cross_scope: false,
        question: "IV is in. What is the appropriate AEMT fluid strategy during this arrest?",
        options: { A: "Saline at TKO rate to maintain access — no bolus without protocol direction", B: "1-liter NS bolus immediately for hypovolemia", C: "D50W to prevent hypoglycemia during prolonged resuscitation", D: "500mL LR bolus for metabolic acidosis" },
        correct: "A",
        rationale_correct: "Fluid boluses in cardiac arrest are not routinely indicated. Keep the line open for ALS medications on intercept.",
        rationale_A: "Correct.",
        rationale_B: "Blind fluid boluses in arrest are not evidence-based.",
        rationale_C: "D50W is only for confirmed hypoglycemia.",
        rationale_D: "LR is not standard in routine cardiac arrest management.",
      },
    ],
    "Paramedic": [
      {
        question_type: "Protocol Knowledge",
        cross_scope: false,
        question: "ETT is placed and confirmed. Ventilation rate post-advanced airway should be:",
        options: { A: "1 breath every 6 seconds (10/min), asynchronous from compressions", B: "2 breaths every 30 compressions, synchronized with CPR", C: "20 breaths per minute to maximize oxygenation", D: "1 breath every 3 seconds (20/min) for drowning patients" },
        correct: "A",
        rationale_correct: "Post-advanced airway: continuous compressions at 100–120/min, ventilate asynchronously at 10/min. Do not pause compressions for breaths.",
        rationale_A: "Correct.",
        rationale_B: "30:2 is BLS without an advanced airway.",
        rationale_C: "20/min causes hyperventilation, increases intrathoracic pressure, and reduces cardiac output.",
        rationale_D: "No different ventilation rate for drowning.",
      },
      {
        question_type: "Assessment",
        cross_scope: false,
        question: "EtCO2 reads 18 mmHg after 2 minutes of CPR. What does this indicate?",
        options: { A: "CPR quality may be inadequate — reassess depth, rate, and recoil", B: "ROSC has occurred — stop compressions and reassess", C: "Patient is hyperventilated — slow the ventilation rate", D: "Epinephrine is working — perfusion is improving" },
        correct: "A",
        rationale_correct: "EtCO2 of 15–20 mmHg suggests suboptimal CPR quality. Target >20 mmHg during resuscitation.",
        rationale_A: "Correct.",
        rationale_B: "ROSC causes a sudden rise to >40 mmHg, not 18.",
        rationale_C: "Low EtCO2 in arrest reflects perfusion, not ventilation rate at 10/min.",
        rationale_D: "Epinephrine can transiently lower EtCO2 by shunting blood to core.",
      },
    ],
  },
  3: {
    "EMT-B": [
      {
        question_type: "Intervention",
        cross_scope: false,
        question: "You are managing the airway while your partner compresses. BVM mask seal is difficult to maintain. Best technique:",
        options: { A: "Two-hand E-C clamp grip while partner manages compressions", B: "Switch to nasal cannula since the mask won't seal", C: "Increase compression rate to generate more pressure", D: "Stop ventilations until an OPA is placed" },
        correct: "A",
        rationale_correct: "Two-provider BVM with E-C clamp provides the best mask seal. One person holds the mask, one compresses.",
        rationale_A: "Correct.",
        rationale_B: "Nasal cannula cannot ventilate an apneic patient.",
        rationale_C: "Compression rate changes don't fix mask seal.",
        rationale_D: "OPA placement should take seconds; stopping ventilations entirely is not acceptable.",
      },
      {
        question_type: "Protocol Knowledge",
        cross_scope: true,
        question: "How long should any interruption to chest compressions last, including rhythm checks?",
        options: { A: "Less than 10 seconds", B: "15–20 seconds maximum", C: "30 seconds is acceptable for intubation", D: "No limit if the intervention is important enough" },
        correct: "A",
        rationale_correct: "All interruptions — rhythm checks, ventilations, pulse checks — must be under 10 seconds per AHA guidelines.",
        rationale_A: "Correct.",
        rationale_B: "15–20 seconds significantly reduces coronary perfusion pressure.",
        rationale_C: "30 seconds is far too long.",
        rationale_D: "Every second without compressions drops coronary perfusion pressure.",
      },
    ],
    "AEMT": [
      {
        question_type: "Assessment",
        cross_scope: false,
        question: "You inserted an OPA and the patient has a gag reflex — surprising in a cardiac arrest. Your response:",
        options: { A: "Remove the OPA immediately and reassess — gag suggests the patient may not be in full arrest", B: "Tape the OPA in place to prevent dislodgement", C: "Suction the oropharynx before re-attempting OPA", D: "Increase BVM pressure to overcome the reflex" },
        correct: "A",
        rationale_correct: "A gag reflex in arrest suggests possible ROSC or the patient was never truly pulseless. Remove OPA and check for pulse immediately.",
        rationale_A: "Correct.",
        rationale_B: "Taping a device that's causing gagging is wrong.",
        rationale_C: "Suctioning may be needed, but a gag reflex first requires reassessment of arrest status.",
        rationale_D: "Forcing ventilation against a gag reflex is inappropriate.",
      },
      {
        question_type: "Assessment",
        cross_scope: true,
        question: "All of the following indicate high-quality CPR EXCEPT:",
        options: { A: "EtCO2 reading of 10 mmHg throughout resuscitation", B: "Full chest recoil between compressions", C: "Compression rate of 110/min", D: "No ventilation pauses longer than 10 seconds" },
        correct: "A",
        rationale_correct: "EtCO2 of 10 indicates poor perfusion — this is a sign of LOW quality CPR, not good CPR. Target >20 mmHg.",
        rationale_A: "Correct — this is the wrong answer, indicating the bad sign.",
        rationale_B: "Full recoil is a quality marker.",
        rationale_C: "110/min is within the guideline range.",
        rationale_D: "Keeping interruptions under 10 seconds is correct.",
      },
    ],
    "Paramedic": [
      {
        question_type: "Intervention",
        cross_scope: false,
        question: "You are preparing to intubate during active CPR. Best practice to minimize interruption:",
        options: { A: "Pause compressions only at the moment of tube passage — aim for under 10 seconds", B: "Pause compressions for up to 30 seconds to ensure first-pass success", C: "Intubate only after ROSC to avoid any CPR interruption", D: "Video laryngoscopy eliminates the need to pause compressions" },
        correct: "A",
        rationale_correct: "Pause only at tube passage. Multiple short attempts beat one long pause. Under 10 seconds is the target.",
        rationale_A: "Correct.",
        rationale_B: "30-second pause collapses coronary perfusion pressure.",
        rationale_C: "Waiting for ROSC means managing the airway with BVM through the entire arrest.",
        rationale_D: "Video laryngoscopy still requires a brief pause — it improves success rate, not pause elimination.",
      },
      {
        question_type: "Clinical Decision",
        cross_scope: false,
        question: "After 2 minutes of CPR, rhythm check shows organized narrow-complex at 80/min. Your next step:",
        options: { A: "Check for a carotid pulse — organized rhythm may mean ROSC", B: "Deliver synchronized cardioversion for narrow-complex rhythm", C: "Give epinephrine 1mg since it hasn't been given yet", D: "Immediately defibrillate the rhythm" },
        correct: "A",
        rationale_correct: "An organized rhythm is ROSC until proven otherwise. Always confirm with a pulse check before treating the rhythm.",
        rationale_A: "Correct.",
        rationale_B: "Never cardiovert without confirming a pulse first.",
        rationale_C: "If ROSC is present, epinephrine causes harmful hypertension. Confirm pulse first.",
        rationale_D: "Never defibrillate an organized rhythm without first confirming pulselessness.",
      },
    ],
  },
  4: {
    "EMT-B": [
      {
        question_type: "Scene Safety",
        cross_scope: true,
        question: "The AED says 'Shock Advised.' The patient is wet from pool water. Before pressing the shock button:",
        options: { A: "Quickly dry the chest and announce 'Clear!' — visually verify no one is touching the patient", B: "Shock immediately without delay since every second in VF matters", C: "Move the patient to completely dry ground even if it takes 2 minutes", D: "Turn off the AED and wait for ALS with a manual defibrillator" },
        correct: "A",
        rationale_correct: "Dry the chest for pad adhesion and safety, then clear the scene of all providers before delivering the shock. This takes only seconds.",
        rationale_A: "Correct.",
        rationale_B: "Shocking a wet patient without drying risks arc burns and poor pad adhesion.",
        rationale_C: "Moving the patient to find dry ground is appropriate but should take seconds, not minutes.",
        rationale_D: "AEDs are effective for VF — do not wait for ALS when you can shock now.",
      },
      {
        question_type: "Protocol Knowledge",
        cross_scope: true,
        question: "Shock delivered. Your immediate next step is:",
        options: { A: "Immediately resume CPR for 2 minutes before reassessing rhythm", B: "Wait 30 seconds then check rhythm", C: "Check for a carotid pulse immediately after the shock", D: "Deliver a second shock in 30 seconds if the patient doesn't wake up" },
        correct: "A",
        rationale_correct: "Post-shock, resume CPR immediately. Do not stop to check rhythm or pulse. Reassess after 2-minute CPR cycle.",
        rationale_A: "Correct.",
        rationale_B: "30-second wait is incorrect — CPR must restart within seconds.",
        rationale_C: "Pulse check happens after 2 minutes of CPR, not immediately post-shock.",
        rationale_D: "Stacked back-to-back shocks are not AHA-recommended.",
      },
    ],
    "AEMT": [
      {
        question_type: "Assessment",
        cross_scope: false,
        question: "AED says 'No Shock Recommended.' Rhythm looks organized with no pulse (PEA). In a drowning arrest, the most treatable cause of PEA is:",
        options: { A: "Hypoxia from submersion-induced respiratory failure", B: "Hyperkalemia from pool chemical aspiration", C: "Cardiac tamponade from CPR-related rib fracture", D: "Pulmonary embolism from immobility" },
        correct: "A",
        rationale_correct: "Drowning arrests are asphyxia-driven. Hypoxia is the primary cause — aggressive oxygenation addresses it directly.",
        rationale_A: "Correct.",
        rationale_B: "Pool chemical hyperkalemia is not a standard drowning H&T consideration.",
        rationale_C: "CPR rib fractures rarely cause hemodynamically significant tamponade.",
        rationale_D: "PE is not related to drowning mechanism.",
      },
      {
        question_type: "Protocol Knowledge",
        cross_scope: false,
        question: "As AEMT, which interventions are within your scope for a PEA arrest?",
        options: { A: "IV/IO access, airway management, high-quality CPR, and ALS handoff", B: "Epinephrine 1mg IV and sodium bicarbonate for acidosis", C: "Bilateral needle decompression to rule out tension pneumo", D: "Synchronized cardioversion of PEA rhythm at 200J" },
        correct: "A",
        rationale_correct: "AEMT scope in PEA = access, airway, CPR quality. Epinephrine and decompression are Paramedic-level.",
        rationale_A: "Correct.",
        rationale_B: "Both medications are outside AEMT scope in most state protocols.",
        rationale_C: "Needle decompression is Paramedic scope.",
        rationale_D: "PEA is non-shockable. Cardioversion has no role.",
      },
    ],
    "Paramedic": [
      {
        question_type: "Protocol Knowledge",
        cross_scope: false,
        question: "VF persists after 3 shocks and 2 doses of epinephrine. The next medication is:",
        options: { A: "Amiodarone 300mg IV push", B: "Lidocaine 1.5mg/kg as the first antiarrhythmic", C: "Magnesium 2g IV for suspected torsades", D: "Atropine 1mg IV for vagally-mediated VF" },
        correct: "A",
        rationale_correct: "Amiodarone 300mg IV push is the first antiarrhythmic for VF/pVT refractory to ≥3 shocks and epinephrine.",
        rationale_A: "Correct.",
        rationale_B: "Lidocaine is an alternative if amiodarone is unavailable, not the first choice.",
        rationale_C: "Magnesium is for torsades de pointes specifically.",
        rationale_D: "Atropine has no role in VF management.",
      },
      {
        question_type: "Clinical Decision",
        cross_scope: false,
        question: "ROSC achieved. Rhythm sinus at 60/min. BP 78/52. Next step:",
        options: { A: "IV fluid resuscitation and vasopressor infusion for post-ROSC hypotension targeting MAP >65", B: "Aspirin 324mg for potential cardiac cause of arrest", C: "Synchronized cardioversion for bradycardia", D: "Atropine 0.5mg for HR of 60" },
        correct: "A",
        rationale_correct: "Post-ROSC hypotension (MAP <65) requires vasopressor support. IV fluid plus vasopressor infusion is the standard post-cardiac arrest treatment.",
        rationale_A: "Correct.",
        rationale_B: "Aspirin is for ACS. Post-drowning ROSC care focuses on hemodynamic stability and oxygenation.",
        rationale_C: "Sinus bradycardia at 60 after ROSC is not an indication for cardioversion.",
        rationale_D: "HR of 60 with a BP of 78/52 — treat the blood pressure, not the heart rate alone.",
      },
    ],
  },
  5: {
    "EMT-B": [
      {
        question_type: "Intervention",
        cross_scope: false,
        question: "ROSC achieved. HR 48, apneic, SpO2 72%. Your airway priority is:",
        options: { A: "Continue BVM with 100% O2, targeting SpO2 94–99%", B: "Place an NRB mask since the patient now has a pulse", C: "Stop ventilations and allow spontaneous breathing to resume", D: "Reduce BVM rate to 1 breath per minute to avoid hyperventilation" },
        correct: "A",
        rationale_correct: "Post-ROSC apneic patients still need assisted ventilation. SpO2 72% demands BVM with 100% FiO2 immediately. Target 94–99%.",
        rationale_A: "Correct.",
        rationale_B: "NRB cannot ventilate an apneic patient.",
        rationale_C: "The patient is not breathing spontaneously — stopping ventilations is dangerous.",
        rationale_D: "SpO2 72% requires adequate ventilation rate, not a reduction.",
      },
      {
        question_type: "Assessment",
        cross_scope: true,
        question: "En route post-ROSC, the patient begins moving and appears to be regaining consciousness. You should:",
        options: { A: "Continue monitoring and be prepared for re-arrest — reassess ABCs frequently", B: "Remove the BVM and switch to NRB since the patient is waking up", C: "Allow the patient to sit upright since they are becoming alert", D: "Discontinue oxygen since SpO2 is now improving" },
        correct: "A",
        rationale_correct: "Post-ROSC patients can re-arrest. Continuous monitoring and frequent reassessment are essential. Airway decisions depend on GCS and SpO2.",
        rationale_A: "Correct.",
        rationale_B: "Transition to NRB may be appropriate if breathing is adequate, but only after confirming adequate SpO2 and respiratory rate.",
        rationale_C: "Position is determined by hemodynamics. With BP 70/40, sitting up is premature.",
        rationale_D: "Continue oxygen until SpO2 is confirmed at target on an appropriate device.",
      },
    ],
    "AEMT": [
      {
        question_type: "Intervention",
        cross_scope: false,
        question: "Post-ROSC: HR 48, BP 70/40, SpO2 72%, apneic. Which AEMT intervention is most critical?",
        options: { A: "Maintain BVM ventilation with 100% O2 and confirm IV access", B: "Administer IV epinephrine to treat the bradycardia", C: "Initiate transcutaneous pacing for bradycardia", D: "Give 1L NS bolus wide open for hypotension" },
        correct: "A",
        rationale_correct: "Apneic patient — ventilation first. IV access for fluid management is AEMT scope. SpO2 72% is the most immediately life-threatening problem.",
        rationale_A: "Correct.",
        rationale_B: "Epinephrine infusion for post-ROSC hypotension is typically Paramedic scope.",
        rationale_C: "Transcutaneous pacing is Paramedic scope.",
        rationale_D: "Fluid boluses can support BP but securing the airway takes priority.",
      },
      {
        question_type: "Assessment",
        cross_scope: false,
        question: "You are monitoring EtCO2 post-ROSC via BVM. It reads 42 mmHg. This indicates:",
        options: { A: "Normal perfusion has returned — continue ventilations and monitor", B: "Hyperventilation — slow the rate immediately", C: "Cardiac re-arrest is imminent", D: "The BVM is leaking — there is no real EtCO2 waveform" },
        correct: "A",
        rationale_correct: "EtCO2 of 40–45 post-ROSC indicates good cardiac output and adequate ventilation. This is a favorable sign.",
        rationale_A: "Correct.",
        rationale_B: "At 10/min, you are not hyperventilating. EtCO2 42 is the target, not a problem.",
        rationale_C: "EtCO2 42 is reassuring, not a pre-arrest sign.",
        rationale_D: "A real waveform at 42 confirms correct tube/BVM placement.",
      },
    ],
    "Paramedic": [
      {
        question_type: "Clinical Decision",
        cross_scope: false,
        question: "Post-ROSC: apneic, HR 48, BP 70/40. Complete post-arrest care bundle includes:",
        options: { A: "Vasopressor infusion for MAP >65, controlled oxygenation at SpO2 94–99%, normocapnia (EtCO2 35–45), and TTM consideration", B: "High-flow O2 at 100% FiO2, epinephrine bolus for BP, atropine for bradycardia, warm blankets", C: "Fluid resuscitation only with 2L NS — no medications until hospital", D: "Defibrillation for sinus bradycardia, then NRB, then IV saline TKO" },
        correct: "A",
        rationale_correct: "Post-ROSC bundle: hemodynamic support (MAP >65), controlled oxygenation (94–99%), normocapnia, and targeted temperature management consideration.",
        rationale_A: "Correct.",
        rationale_B: "100% FiO2 causes hyperoxia and worsens neurological outcomes. Atropine for post-ROSC bradycardia is not standard.",
        rationale_C: "Fluids alone are insufficient without vasopressors for adequate MAP.",
        rationale_D: "Never defibrillate sinus bradycardia.",
      },
      {
        question_type: "Assessment",
        cross_scope: false,
        question: "EtCO2 is 18 post-ROSC. You are ventilating at 10/min. This most likely indicates:",
        options: { A: "Poor cardiac output — reassess hemodynamics and vasopressor support", B: "Hyperventilation — reduce rate immediately", C: "The patient is in respiratory alkalosis — slow to 4/min", D: "ROSC is not confirmed — check pulse immediately" },
        correct: "A",
        rationale_correct: "Post-ROSC EtCO2 of 18 at a normal ventilation rate reflects inadequate cardiac output, not a ventilation problem. Reassess BP and vasopressor support.",
        rationale_A: "Correct.",
        rationale_B: "10/min is not hyperventilation. Low EtCO2 here is a perfusion issue.",
        rationale_C: "Slowing to 4/min would cause dangerous hypoventilation.",
        rationale_D: "EtCO2 of 18 is low but doesn't negate ROSC — address hemodynamics.",
      },
    ],
  },
};

// ─── DKA ─────────────────────────────────────────────────────────────────────

export const DKA_QUESTIONS: Record<number, StepQuestions> = {
  1: {
    "EMT-B": [
      {
        question_type: "Assessment",
        cross_scope: true,
        question: "You notice deep rapid breathing and a fruity acetone odor. This breathing pattern is called:",
        options: { A: "Kussmaul respirations — compensatory response to metabolic acidosis", B: "Cheyne-Stokes respirations indicating brain herniation", C: "Agonal respirations requiring immediate BVM ventilation", D: "Biot's respirations from increased intracranial pressure" },
        correct: "A",
        rationale_correct: "Kussmaul respirations are deep, regular breaths the body uses to blow off CO2 and compensate for metabolic acidosis in DKA.",
        rationale_A: "Correct.",
        rationale_B: "Cheyne-Stokes is a cyclic pattern of apnea/hyperpnea seen in stroke or heart failure.",
        rationale_C: "Agonal breathing is gasping and irregular. Kussmaul is deep and regular — not a BVM indication in a conscious patient.",
        rationale_D: "Biot's (cluster breathing with apneic pauses) indicates raised ICP.",
      },
      {
        question_type: "Clinical Decision",
        cross_scope: false,
        question: "Blood glucose reads 'HI' (>500 mg/dL). As EMT-B, your field treatment is:",
        options: { A: "Supportive care, oxygen if SpO2 <94%, and rapid transport", B: "Oral glucose tablets since the patient is diabetic", C: "IV insulin to lower blood sugar", D: "NRB at 15 LPM regardless of SpO2" },
        correct: "A",
        rationale_correct: "EMT-B treatment for DKA is supportive — monitor, oxygen if needed, and transport. Insulin and IV fluids are ALS/hospital treatments.",
        rationale_A: "Correct.",
        rationale_B: "Oral glucose is absolutely contraindicated in hyperglycemia.",
        rationale_C: "IV insulin is not within EMT-B scope.",
        rationale_D: "NRB is not indicated with SpO2 96% on room air.",
      },
    ],
    "AEMT": [
      {
        question_type: "Intervention",
        cross_scope: false,
        question: "BGL >500, patient deteriorating. As AEMT, your most appropriate intervention is:",
        options: { A: "Establish IV access and begin normal saline infusion — call for ALS intercept", B: "Administer D50W IV — glucose may be falsely elevated", C: "Insert an NPA to assist her Kussmaul breathing", D: "Give sodium bicarbonate IV for metabolic acidosis" },
        correct: "A",
        rationale_correct: "AEMT scope includes IV access and fluid therapy. NS addresses dehydration from osmotic diuresis. ALS intercept for insulin and closer management.",
        rationale_A: "Correct.",
        rationale_B: "D50 in hyperglycemia is absolutely contraindicated.",
        rationale_C: "Kussmaul breathing is compensatory — do not interfere unless the patient becomes apneic.",
        rationale_D: "Sodium bicarbonate is not a standard field treatment for DKA.",
      },
      {
        question_type: "Clinical Decision",
        cross_scope: false,
        question: "SpO2 is 96% on room air, RR 28 (Kussmaul). What is the appropriate oxygen delivery?",
        options: { A: "Low-flow nasal cannula only if SpO2 drops below 94%", B: "Non-rebreather mask at 15 LPM immediately", C: "BVM ventilations at 1 breath every 5 seconds", D: "No oxygen needed since SpO2 is above 90%" },
        correct: "A",
        rationale_correct: "SpO2 96% does not require supplemental oxygen. Titrate to maintain 94–99%. Unnecessary high-flow O2 causes oxidative harm.",
        rationale_A: "Correct.",
        rationale_B: "NRB is unnecessary with SpO2 96%.",
        rationale_C: "BVM is for apneic or severely hypoxic patients. Kussmaul is compensation, not failure.",
        rationale_D: "Correct instinct but be ready to add O2 if SpO2 drops.",
      },
    ],
    "Paramedic": [
      {
        question_type: "Intervention",
        cross_scope: false,
        question: "Paramedic-level initial fluid resuscitation for DKA should be:",
        options: { A: "0.9% Normal saline 20 mL/kg bolus, then reassess", B: "D5W to prevent cellular dehydration", C: "0.45% half-normal saline as initial resuscitation fluid", D: "Lactated Ringer's at 150 mL/hr maximum" },
        correct: "A",
        rationale_correct: "Normal saline is the initial resuscitation fluid of choice in DKA. A 15–20 mL/kg (approximately 1L in adults) bolus is standard ALS field care.",
        rationale_A: "Correct.",
        rationale_B: "D5W in hyperglycemia is contraindicated.",
        rationale_C: "0.45% NaCl is used after initial resuscitation in DKA, not as the first-line field fluid.",
        rationale_D: "150 mL/hr is far too slow for initial resuscitation.",
      },
      {
        question_type: "Assessment",
        cross_scope: false,
        question: "Which finding in this pediatric DKA patient would most change your transport priority?",
        options: { A: "Worsening level of consciousness or new focal neurological signs", B: "Kussmaul respirations becoming deeper and faster", C: "Blood glucose still reading HI after 15 minutes", D: "HR increasing from 118 to 124 en route" },
        correct: "A",
        rationale_correct: "Cerebral edema is a life-threatening DKA complication, especially in pediatric patients. Declining mental status or focal neuro signs require immediate aggressive transport.",
        rationale_A: "Correct.",
        rationale_B: "Worsening Kussmaul suggests worsening acidosis but is compensatory — concerning, but cerebral edema is more immediately life-threatening.",
        rationale_C: "Glucose will not normalize without insulin. Persistent high glucose is expected en route.",
        rationale_D: "A slight HR increase reflects physiological stress; not alarming in isolation.",
      },
    ],
  },
  2: {
    "EMT-B": [
      {
        question_type: "Assessment",
        cross_scope: true,
        question: "The patient responds to your voice but is confused and slow. On AVPU she is rated:",
        options: { A: "V — responds to Voice", B: "A — Alert", C: "P — responds to Pain", D: "U — Unresponsive" },
        correct: "A",
        rationale_correct: "Responds to verbal stimulus but not fully alert = 'V' on AVPU.",
        rationale_A: "Correct.",
        rationale_B: "Alert means fully awake and oriented. She is confused, not alert.",
        rationale_C: "P is assigned only when a painful stimulus is required for response.",
        rationale_D: "U is for completely unresponsive patients.",
      },
      {
        question_type: "Communication",
        cross_scope: false,
        question: "The parents ask if they should give her insulin now. Your response:",
        options: { A: "'No — field crews don't administer insulin. We're starting an IV and getting her to the hospital where they can treat her properly.'", B: "'Yes, give her usual insulin dose immediately.'", C: "'Give her orange juice and sugar to balance the insulin she's missing.'", D: "'Wait for the ALS unit to assess her before any treatment.'" },
        correct: "A",
        rationale_correct: "Insulin is not an EMT-B medication. Educate the family calmly and focus on transport.",
        rationale_A: "Correct.",
        rationale_B: "Insulin without IV access and hospital monitoring is dangerous.",
        rationale_C: "Orange juice is for hypoglycemia, the opposite of this patient's problem.",
        rationale_D: "Don't delay treatment or transport waiting for ALS.",
      },
    ],
    "AEMT": [
      {
        question_type: "Assessment",
        cross_scope: false,
        question: "GCS is 12 (E3V4M5). This mental status finding indicates:",
        options: { A: "Significant CNS involvement — ALS intercept is appropriate", B: "GCS 12 is normal for a sick teenager — no escalation needed", C: "Immediate intubation to protect the airway", D: "Administer D50W since GCS <15 suggests hypoglycemia" },
        correct: "A",
        rationale_correct: "GCS 12 in a DKA patient indicates significant CNS involvement. ALS intercept is appropriate for ongoing assessment and insulin consideration.",
        rationale_A: "Correct.",
        rationale_B: "GCS 12 is NOT normal. Baseline is 15.",
        rationale_C: "GCS 12 with a gag reflex does not require intubation. Protect airway and monitor.",
        rationale_D: "BGL is already confirmed >500. D50 is absolutely contraindicated.",
      },
      {
        question_type: "Assessment",
        cross_scope: true,
        question: "Patient skin is dry, warm, and tents when pinched. This indicates:",
        options: { A: "Significant dehydration from osmotic diuresis secondary to hyperglycemia", B: "Normal skin finding for a teenager with Type 1 diabetes", C: "Third-degree burns from prolonged hyperglycemia", D: "Anaphylactic reaction to insulin she may have taken" },
        correct: "A",
        rationale_correct: "Osmotic diuresis in DKA causes profound dehydration. Dry, tented skin is a classic finding. IV fluid resuscitation addresses this directly.",
        rationale_A: "Correct.",
        rationale_B: "Skin tenting is abnormal and indicates dehydration.",
        rationale_C: "Hyperglycemia does not cause skin burns.",
        rationale_D: "Anaphylaxis presents with hives, angioedema, or hemodynamic collapse.",
      },
    ],
    "Paramedic": [
      {
        question_type: "Assessment",
        cross_scope: false,
        question: "GCS 12 in a pediatric DKA patient. Which cerebral complication requires the highest vigilance?",
        options: { A: "Cerebral edema — most common in pediatric DKA, can cause rapid herniation", B: "Subarachnoid hemorrhage — DKA increases bleeding risk", C: "Hypertensive encephalopathy — BP is usually elevated in DKA", D: "Status epilepticus — DKA lowers seizure threshold universally" },
        correct: "A",
        rationale_correct: "Cerebral edema is rare but deadly in DKA, especially in pediatric patients. It's associated with too-rapid fluid resuscitation. Monitor for declining GCS, headache, and bradycardia.",
        rationale_A: "Correct.",
        rationale_B: "Subarachnoid hemorrhage is not a DKA complication.",
        rationale_C: "BP in DKA is typically LOW due to dehydration.",
        rationale_D: "Seizures can occur in severe DKA but status epilepticus is not a primary DKA-specific complication.",
      },
      {
        question_type: "Protocol Knowledge",
        cross_scope: false,
        question: "Which electrolyte abnormality is the most dangerous during DKA treatment with insulin?",
        options: { A: "Hypokalemia — insulin drives potassium into cells, worsening total-body depletion", B: "Hypernatremia — DKA causes sharp sodium rises in all patients", C: "Hypercalcemia — acidosis releases calcium from bone", D: "Hypophosphatemia — only a concern in alcoholic ketoacidosis" },
        correct: "A",
        rationale_correct: "DKA patients are total-body potassium depleted despite normal or elevated serum K+. Insulin therapy drives K+ intracellularly, risking dangerous hypokalemia. Monitor ECG.",
        rationale_A: "Correct.",
        rationale_B: "Sodium in DKA is typically low (dilutional hyponatremia from hyperglycemia-induced water shifts).",
        rationale_C: "Calcium shifts in DKA are not clinically significant in the field.",
        rationale_D: "Hypophosphatemia occurs in DKA as well, not exclusively in alcoholic KA.",
      },
    ],
  },
  3: {
    "EMT-B": [
      {
        question_type: "Assessment",
        cross_scope: true,
        question: "SpO2 reads 96% on room air, RR 28 (Kussmaul). What oxygen therapy is indicated right now?",
        options: { A: "No supplemental oxygen — SpO2 96% is within target range; monitor closely", B: "NRB at 15 LPM — all DKA patients need high-flow oxygen", C: "BVM ventilations at 10 breaths per minute", D: "Nasal cannula at 2 LPM as a precaution" },
        correct: "A",
        rationale_correct: "SpO2 96% is within the 94–99% target. Supplemental oxygen is not indicated. Avoid hyperoxia. Reassess if SpO2 drops.",
        rationale_A: "Correct.",
        rationale_B: "High-flow O2 without indication causes oxidative harm.",
        rationale_C: "BVM is for apneic or severely hypoxic patients.",
        rationale_D: "2 LPM nasal cannula is not indicated when SpO2 is already at target.",
      },
      {
        question_type: "Clinical Decision",
        cross_scope: false,
        question: "HR 118, BP 98/64. This vital sign combination in a DKA patient suggests:",
        options: { A: "Dehydration-driven compensated shock — fluid resuscitation is the priority", B: "Normal hemodynamics for a 17-year-old — no concern", C: "Neurogenic shock from cerebral edema", D: "Hypertensive urgency requiring immediate antihypertensive treatment" },
        correct: "A",
        rationale_correct: "Tachycardia with low-normal BP in DKA indicates volume depletion and compensated shock from osmotic diuresis. IV fluids are the field priority.",
        rationale_A: "Correct.",
        rationale_B: "HR 118 and BP 98/64 are not normal for this patient.",
        rationale_C: "Neurogenic shock produces bradycardia, not tachycardia.",
        rationale_D: "BP 98/64 is not hypertensive.",
      },
    ],
    "AEMT": [
      {
        question_type: "Intervention",
        cross_scope: false,
        question: "You need IV access but the patient is severely dehydrated with collapsed veins. Best approach:",
        options: { A: "Attempt an antecubital or external jugular site — consider IO if two attempts fail", B: "Place a central line via subclavian approach", C: "Abandon IV and rely on oral hydration", D: "Delay treatment and transport rapidly to the hospital" },
        correct: "A",
        rationale_correct: "AC or EJ are preferred peripheral sites in dehydrated patients. IO is a valid AEMT option if peripheral access fails after two attempts.",
        rationale_A: "Correct.",
        rationale_B: "Central lines are not AEMT scope.",
        rationale_C: "Oral hydration is inadequate for this degree of dehydration.",
        rationale_D: "Attempting IV access en route is appropriate — don't delay transport, but work the problem.",
      },
      {
        question_type: "Protocol Knowledge",
        cross_scope: false,
        question: "IV access achieved. Which fluid and rate is most appropriate for this DKA patient at AEMT scope?",
        options: { A: "Normal saline bolus — rate and volume per local protocol, typically 20 mL/kg", B: "D5W at 125 mL/hr maintenance rate", C: "Lactated Ringer's at 30 mL/hr to avoid over-hydration", D: "No fluids until insulin is started at the hospital" },
        correct: "A",
        rationale_correct: "Normal saline is the initial DKA fluid. An initial bolus (approximately 20 mL/kg) addresses acute dehydration per most AEMT protocols.",
        rationale_A: "Correct.",
        rationale_B: "D5W is contraindicated in hyperglycemia.",
        rationale_C: "30 mL/hr is far too slow for a patient who is hemodynamically compromised from DKA dehydration.",
        rationale_D: "Fluids are critical before insulin — starting insulin without addressing hypovolemia is dangerous.",
      },
    ],
    "Paramedic": [
      {
        question_type: "Assessment",
        cross_scope: false,
        question: "You apply the cardiac monitor to this DKA patient. Which ECG finding would most concern you given her electrolyte status?",
        options: { A: "Peaked T-waves or widened QRS suggesting hyperkalemia", B: "Sinus tachycardia at 118 bpm", C: "PR interval 0.20 seconds", D: "QTc interval of 420ms" },
        correct: "A",
        rationale_correct: "DKA patients can have paradoxically elevated serum K+ initially (acidosis shifts K+ extracellularly). Peaked T-waves or wide QRS indicates dangerous hyperkalemia requiring immediate attention.",
        rationale_A: "Correct.",
        rationale_B: "Sinus tach at 118 is expected in this dehydrated, ill patient.",
        rationale_C: "PR of 0.20s is the upper limit of normal — not alarming here.",
        rationale_D: "QTc 420ms is within normal range.",
      },
      {
        question_type: "Clinical Decision",
        cross_scope: false,
        question: "ALS intercept is 8 minutes away. Your fluid resuscitation plan for this 17-year-old (approximately 55kg) in DKA:",
        options: { A: "Normal saline 1100 mL (20 mL/kg) bolus over 20–30 minutes, then reassess", B: "Normal saline 500 mL bolus then switch to D5W once glucose drops below 300", C: "Half-normal saline 2L bolus to avoid sodium overload", D: "Withhold fluids until the ALS unit can assess her" },
        correct: "A",
        rationale_correct: "20 mL/kg NS (~1100 mL for 55kg) is the standard initial resuscitation bolus in DKA. Reassess after each bolus. D5 is added in-hospital once glucose <250–300.",
        rationale_A: "Correct.",
        rationale_B: "D5W in the field during hyperglycemia is contraindicated.",
        rationale_C: "0.45% NaCl is not the first-line initial bolus fluid.",
        rationale_D: "Delaying fluids for ALS arrival worsens dehydration and hemodynamics.",
      },
    ],
  },
  4: {
    "EMT-B": [
      {
        question_type: "Clinical Decision",
        cross_scope: false,
        question: "Patient is deteriorating with BP 92/58 and SpO2 95%. ALS intercept is 10 minutes out. Your transport decision is:",
        options: { A: "Load and go immediately — do not delay transport for procedures that can be done en route", B: "Remain on scene until ALS arrives — this patient is too critical to move", C: "Discharge the patient to family care with DKA education", D: "Call medical direction and wait for instructions before moving" },
        correct: "A",
        rationale_correct: "Deteriorating DKA with hemodynamic compromise requires rapid transport. Procedures like IV access can and should be done en route. Load and go.",
        rationale_A: "Correct.",
        rationale_B: "Remaining on scene delays definitive care. ALS intercept can meet you en route.",
        rationale_C: "This patient is critically ill and cannot be discharged.",
        rationale_D: "While medical direction is available, hemodynamic compromise is a clear transport indication. Don't delay for a phone call.",
      },
      {
        question_type: "Assessment",
        cross_scope: true,
        question: "Which destination is most appropriate for this critically ill DKA patient?",
        options: { A: "Nearest emergency department with adult/pediatric ED capabilities", B: "Urgent care clinic since this is a medical (not trauma) problem", C: "The patient's primary care physician's office", D: "The hospital where her endocrinologist practices, even if it is 45 minutes farther" },
        correct: "A",
        rationale_correct: "The nearest appropriate ED is the correct destination. Critically ill DKA patients need immediate IV fluid resuscitation and insulin therapy — delay to a farther hospital is dangerous.",
        rationale_A: "Correct.",
        rationale_B: "Urgent care cannot manage critically ill DKA.",
        rationale_C: "Primary care offices cannot manage this emergency.",
        rationale_D: "45 additional minutes for a deteriorating patient is not acceptable.",
      },
    ],
    "AEMT": [
      {
        question_type: "Intervention",
        cross_scope: false,
        question: "Patient is becoming less responsive (GCS dropping from 12 to 10). IV fluids are running. Your next AEMT intervention:",
        options: { A: "Reassess airway and breathing — be prepared to support ventilation if GCS drops further", B: "Administer dextrose 50% IV since declining GCS suggests hypoglycemia", C: "Administer naloxone — altered mental status may be opioid-related", D: "Increase IV fluid rate to maximum to improve brain perfusion" },
        correct: "A",
        rationale_correct: "Declining GCS in DKA means the airway may be at risk. Position the patient, have suction ready, and prepare to assist ventilation if GCS drops to ≤8.",
        rationale_A: "Correct.",
        rationale_B: "BGL is confirmed >500. D50 is absolutely contraindicated.",
        rationale_C: "No opioid indication here. Naloxone is not appropriate.",
        rationale_D: "Increasing fluid rate does not directly improve brain perfusion in DKA cerebral edema — it may worsen it.",
      },
      {
        question_type: "Clinical Decision",
        cross_scope: false,
        question: "ALS intercept is now confirmed 6 minutes out. What information is most critical to relay to the incoming ALS unit?",
        options: { A: "Mechanism, BGL >500, GCS declining from 12 to 10, current VS, and IV access established with NS running", B: "Patient name, insurance information, and primary care doctor contact", C: "Family history of diabetes and whether the patient has been hospitalized before", D: "The exact address where the patient was found" },
        correct: "A",
        rationale_correct: "ALS needs the clinical picture: mechanism, BGL, mental status trend, vital signs, and what treatment is in progress. This allows them to prepare medications and interventions before arrival.",
        rationale_A: "Correct.",
        rationale_B: "Administrative information is not clinically useful for ALS intercept.",
        rationale_C: "Family history is not an intercept priority.",
        rationale_D: "ALS already has the address from dispatch.",
      },
    ],
    "Paramedic": [
      {
        question_type: "Clinical Decision",
        cross_scope: false,
        question: "GCS has dropped to 10 and the patient now has Kussmaul respirations at 34/min. Should you intubate?",
        options: { A: "Not yet — support ventilation with BVM if needed, but intubation can worsen acidosis and mask neurological exam", B: "Yes — any GCS below 12 is an automatic intubation indication", C: "Yes — intubate and hyperventilate to 20/min to blow off CO2 and correct the acidosis", D: "Yes — intubate and ventilate at 4/min to allow CO2 to rise and buffer the acidosis" },
        correct: "A",
        rationale_correct: "Intubation in DKA is a last resort. Removing the patient's ability to breathe spontaneously eliminates their compensatory mechanism. Support ventilation with BVM if needed. Intubate if GCS ≤8 with airway compromise.",
        rationale_A: "Correct.",
        rationale_B: "GCS 10 with a patent airway and adequate SpO2 is not an automatic intubation trigger.",
        rationale_C: "Hyperventilation in DKA worsens outcomes — it does not correct metabolic acidosis.",
        rationale_D: "Slowing ventilation causes dangerous hypercapnia on top of existing metabolic acidosis.",
      },
      {
        question_type: "Protocol Knowledge",
        cross_scope: false,
        question: "This is a pediatric DKA patient. Regarding IV fluid resuscitation, which practice most reduces the risk of cerebral edema?",
        options: { A: "Avoid overly aggressive fluid boluses — give 10–20 mL/kg then reassess rather than running fluids wide open", B: "Give as much fluid as possible as fast as possible to correct dehydration", C: "Switch to hypotonic 0.45% saline for all pediatric DKA patients from the start", D: "Restrict all fluids until the patient reaches the hospital" },
        correct: "A",
        rationale_correct: "Overly rapid fluid resuscitation is associated with cerebral edema in pediatric DKA. Give defined boluses and reassess rather than wide-open infusion.",
        rationale_A: "Correct.",
        rationale_B: "Wide-open fluid administration is associated with cerebral edema in pediatric DKA.",
        rationale_C: "0.45% NaCl is used later in management, not as initial resuscitation.",
        rationale_D: "Fluid restriction is dangerous — these patients are profoundly dehydrated.",
      },
    ],
  },
  5: {
    "EMT-B": [
      {
        question_type: "Assessment",
        cross_scope: true,
        question: "En route with IV NS running, BP improves slightly to 96/62. How often should you reassess vital signs?",
        options: { A: "Every 5 minutes for an unstable patient", B: "Once at the beginning and once on arrival to the ED", C: "Only if the patient reports a change in symptoms", D: "Every 15 minutes is sufficient for a medical patient" },
        correct: "A",
        rationale_correct: "Unstable or critical patients require vital signs every 5 minutes. This patient is deteriorating and on IV fluid therapy — frequent reassessment catches changes early.",
        rationale_A: "Correct.",
        rationale_B: "Single-point vital signs are insufficient for a critically ill patient.",
        rationale_C: "Waiting for patient-reported changes is passive and unsafe.",
        rationale_D: "15-minute intervals are for stable patients. This patient is not stable.",
      },
      {
        question_type: "Clinical Decision",
        cross_scope: false,
        question: "Mental status worsens suddenly en route — patient now only responds to pain. You should:",
        options: { A: "Immediately reassess airway, position patient, call ED, and prepare to assist ventilation", B: "Administer D50W — sudden decline suggests hypoglycemia despite the BGL reading", C: "Pull over and wait for ALS to arrive before moving", D: "Continue transport and document the decline for the ED" },
        correct: "A",
        rationale_correct: "Sudden decline to P on AVPU in DKA may indicate cerebral edema. Airway is the immediate priority. Notify the ED early. Prepare to assist ventilation.",
        rationale_A: "Correct.",
        rationale_B: "BGL is confirmed >500. D50 is contraindicated regardless of mental status.",
        rationale_C: "Stopping transport delays definitive care. Continue and manage airway en route.",
        rationale_D: "Documentation alone is insufficient — active airway management is needed now.",
      },
    ],
    "AEMT": [
      {
        question_type: "Assessment",
        cross_scope: false,
        question: "IV NS is running at approximately 20 mL/kg. How do you know if fluid resuscitation is working?",
        options: { A: "Improving BP, decreasing HR, and improving mental status (GCS trending back toward 15)", B: "Blood glucose dropping below 200 mg/dL", C: "Kussmaul breathing resolving to a normal rate", D: "Patient reports feeling better" },
        correct: "A",
        rationale_correct: "The goal of field fluid resuscitation in DKA is hemodynamic improvement — better BP and HR, and improving mental status. Glucose doesn't normalize without insulin.",
        rationale_A: "Correct.",
        rationale_B: "Glucose will not drop without insulin. Don't use glucose as a fluid resuscitation endpoint.",
        rationale_C: "Kussmaul breathing will persist as long as metabolic acidosis is present — it resolves only with insulin therapy.",
        rationale_D: "Subjective improvement alone is not a reliable endpoint.",
      },
      {
        question_type: "Clinical Decision",
        cross_scope: false,
        question: "ALS arrives and takes over. Your handoff should include all of the following EXCEPT:",
        options: { A: "The patient's full insurance and billing information", B: "Blood glucose reading and trend", C: "Current mental status (GCS 10 and declining)", D: "IV access site, fluid type, and volume infused" },
        correct: "A",
        rationale_correct: "Clinical handoff focuses on patient condition, treatments given, and trends — not billing information. Insurance details are handled administratively.",
        rationale_A: "Correct — this is NOT needed in the clinical handoff.",
        rationale_B: "BGL and trend are critical for ALS to know.",
        rationale_C: "Mental status trend is one of the most important data points.",
        rationale_D: "IV site, fluid type, and volume infused are essential for continuity of care.",
      },
    ],
    "Paramedic": [
      {
        question_type: "Assessment",
        cross_scope: false,
        question: "En route, you notice the patient has bradycardia developing (HR 52 from 116). Combined with her declining GCS, this pattern suggests:",
        options: { A: "Cerebral edema with Cushing's triad (bradycardia, hypertension, irregular respirations)", B: "Hypovolemia worsening — bradycardia indicates severe volume depletion", C: "The IV fluids are working and the heart rate is normalizing", D: "Normal autonomic variation during metabolic acidosis correction" },
        correct: "A",
        rationale_correct: "Bradycardia + declining GCS in a DKA patient is Cushing's triad until proven otherwise. This indicates cerebral edema with herniation. Treat as a neurological emergency.",
        rationale_A: "Correct.",
        rationale_B: "Hypovolemia causes tachycardia, not bradycardia.",
        rationale_C: "Bradycardia from 116 to 52 during fluid resuscitation is not a sign of improvement.",
        rationale_D: "This is not a normal variation. This pattern is dangerous.",
      },
      {
        question_type: "Clinical Decision",
        cross_scope: false,
        question: "You suspect cerebral edema. Which Paramedic intervention is most appropriate en route?",
        options: { A: "Reduce fluid rate, elevate head of bed 30 degrees, notify receiving ED immediately, prepare for intubation", B: "Increase fluid rate — cerebral edema is caused by inadequate fluid resuscitation", C: "Administer D50W to treat the presumed cerebral glucose deficit", D: "Give IV sodium bicarbonate to correct the metabolic acidosis driving the edema" },
        correct: "A",
        rationale_correct: "Suspected DKA cerebral edema: slow fluids (over-rapid infusion is a cause), position with HOB 30°, notify ED for mannitol or hypertonic saline preparation, and prepare for airway management.",
        rationale_A: "Correct.",
        rationale_B: "Increased fluids worsen cerebral edema in DKA.",
        rationale_C: "D50 is absolutely contraindicated in this patient.",
        rationale_D: "Sodium bicarbonate does not treat cerebral edema and is not routinely indicated in DKA.",
      },
    ],
  },
};
