import { storage } from "./storage";
import { db } from "./db";
import { scenarios } from "@shared/schema";
import { log } from "./index";

export async function seedDatabase() {
  const existing = await db.select().from(scenarios).limit(1);
  if (existing.length > 0) {
    log("Database already seeded", "seed");
    return;
  }

  log("Seeding database with EMS scenarios...", "seed");

  const scenario1 = await storage.createScenario({
    title: "Sports Injury - Rib Fracture",
    description: "A 22-year-old female soccer player has fallen during a game after being struck by another player's elbow. She is sitting on the ground holding her left side and breathing rapidly.",
    patientSummary: "22F, conscious, rapid breathing, left-side rib pain after blunt trauma during soccer game.",
    difficulty: "Beginner",
    category: "Trauma",
    certLevel: "EMT",
    imageUrl: "/images/scenario-sports-injury.png",
    estimatedMinutes: 8,
    tags: ["trauma", "rib injury", "primary assessment", "scene safety"],
    departureVideoUrl: "/videos/s1-departure.mp4",
  });

  await Promise.all([
    storage.createScenarioStep({
      scenarioId: scenario1.id,
      stepOrder: 1,
      phase: "Scene Safety",
      prompt: "You arrive on scene at a soccer field. A player is sitting on the ground holding her side. What is your first action?",
      patientState: "A 22-year-old female is sitting on the ground holding her left side. Teammates surround her, looking concerned.",
      vitalSigns: null,
      correctActions: ["Don BSI/PPE (gloves, eye protection) and assess scene safety"],
      incorrectActions: [
        "Run directly to the patient without PPE",
        "Call for ALS immediately",
        "Begin spinal immobilization",
      ],
      feedbackCorrect: "Excellent! BSI and scene safety always come first. You need to protect yourself before you can help anyone else.",
      feedbackIncorrect: "Always start with BSI/PPE and scene safety. Your safety comes first - you can't help the patient if you become one.",
      hint: "Think about what you always do FIRST at every single scene.",
      isCritical: false,
      videoUrl: "/videos/s1-step1-arrive-soccer.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario1.id,
      stepOrder: 2,
      phase: "Scene Size-Up",
      prompt: "Your scene is safe. You see one patient on the ground. Her teammates report she was struck in the ribs by another player's elbow. What do you determine about additional resources?",
      patientState: "The patient is alert, talking to teammates, holding her left side. No other injured players visible.",
      vitalSigns: null,
      correctActions: ["Determine there is 1 patient, MOI is blunt trauma to ribs, no ALS needed at this time"],
      incorrectActions: [
        "Call for fire department extrication",
        "Request hazmat team",
        "Immediately call for helicopter transport",
      ],
      feedbackCorrect: "Good assessment. Single patient with a clear mechanism of injury. No need for additional specialized resources at this point.",
      feedbackIncorrect: "For a simple blunt trauma on a sports field, you don't need specialized resources. Assess the MOI: an elbow strike to the ribs is the mechanism.",
      hint: "How many patients? What caused the injury? Do you need backup?",
      isCritical: false,
      videoUrl: "/videos/s1-step2-walk-to-player.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario1.id,
      stepOrder: 3,
      phase: "General Impression",
      prompt: "You approach the patient. She is alert, talking, and holding her left side. What is your general impression?",
      patientState: "Patient is alert and verbal. She winces when breathing. No visible bleeding or deformity. She is sitting upright.",
      vitalSigns: null,
      correctActions: ["Patient is alert (A on AVPU), no immediate life threats visible, the patient appears to be in pain but stable"],
      incorrectActions: [
        "Patient is unresponsive and needs CPR",
        "Patient has a major hemorrhage requiring a tourniquet",
        "Patient needs immediate spinal immobilization",
      ],
      feedbackCorrect: "Correct! The patient is alert on the AVPU scale, talking, and while in pain, has no immediately apparent life threats.",
      feedbackIncorrect: "Look at the patient more carefully. She is sitting up, talking, and holding her side. She is clearly alert and has no major visible life threats.",
      hint: "Is the patient Alert, responding to Voice, Pain, or Unresponsive? Any obvious life threats?",
      isCritical: false,
      videoUrl: "/videos/s1-step3-approach-patient.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario1.id,
      stepOrder: 4,
      phase: "Primary Assessment",
      prompt: "Assess the patient's airway. What do you find?",
      patientState: "The patient is speaking to you in short sentences between winces of pain. Her voice is clear.",
      vitalSigns: null,
      correctActions: ["The airway is patent - the patient is speaking clearly"],
      incorrectActions: [
        "The airway is obstructed, perform head-tilt chin-lift",
        "Insert an OPA immediately",
        "Suction the airway",
      ],
      feedbackCorrect: "Correct! If the patient can speak, the airway is patent. No intervention needed at this time.",
      feedbackIncorrect: "The patient is speaking clearly to you. A speaking patient has a patent airway. No airway interventions are needed.",
      hint: "Can the patient speak? What does that tell you about the airway?",
      isCritical: false,
      videoUrl: "/videos/s1-step4-check-airway.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario1.id,
      stepOrder: 5,
      phase: "Primary Assessment",
      prompt: "Assess breathing. You notice the patient is breathing rapidly and shallowly. Vitals show RR 32, SpO2 88%. What is your intervention?",
      patientState: "Patient is breathing rapidly at 32 breaths per minute with shallow respirations. She guards her left side with each breath.",
      vitalSigns: { hr: 124, rr: 32, spo2: 88, skinColor: "Pale", skinTemp: "Cool", skinMoisture: "Diaphoretic" },
      correctActions: ["Administer high-flow oxygen via non-rebreather mask at 15 LPM"],
      incorrectActions: [
        "Administer oxygen via nasal cannula at 2 LPM",
        "No oxygen needed, the patient is breathing",
        "Begin assisted ventilations with BVM",
      ],
      feedbackCorrect: "Excellent! With an SpO2 of 88% and rapid shallow breathing, high-flow oxygen via non-rebreather at 15 LPM is the correct intervention.",
      feedbackIncorrect: "With an SpO2 of 88% and a respiratory rate of 32, the patient needs high-flow oxygen. A non-rebreather at 15 LPM is appropriate for this level of hypoxia.",
      hint: "The SpO2 is 88%. What oxygen delivery device is appropriate for significant hypoxia?",
      isCritical: true,
      videoUrl: "/videos/s1-step5-check-breathing.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario1.id,
      stepOrder: 6,
      phase: "Primary Assessment",
      prompt: "Assess circulation. The patient's pulse is 124, skin is cool and diaphoretic. How do you interpret and prioritize this patient?",
      patientState: "Pulse is rapid at 124. Skin is cool, pale, and diaphoretic. Capillary refill is 3 seconds.",
      vitalSigns: { hr: 124, rr: 32, spo2: 88, bp: "96/62", skinColor: "Pale", skinTemp: "Cool", skinMoisture: "Diaphoretic" },
      correctActions: ["Signs indicate possible shock (tachycardia, cool/diaphoretic skin, hypotension). This is a HIGH priority patient - prepare for rapid transport"],
      incorrectActions: [
        "This is a low priority patient, transport at convenience",
        "The vitals are normal, continue assessment on scene",
        "Administer aspirin for the elevated heart rate",
      ],
      feedbackCorrect: "Correct! Tachycardia, cool/diaphoretic skin, and hypotension (96/62) are classic signs of shock. This patient needs rapid transport to a trauma center.",
      feedbackIncorrect: "A heart rate of 124, cool/diaphoretic skin, and a blood pressure of 96/62 are signs of compensated shock. This is a high priority patient requiring rapid transport.",
      hint: "What do tachycardia, cool skin, and low blood pressure indicate together?",
      isCritical: true,
      videoUrl: "/videos/s1-step6-check-circulation.mp4",
    }),
  ]);

  const scenario2 = await storage.createScenario({
    title: "Pediatric Asthma Attack",
    description: "A 6-year-old male is sitting upright, appearing anxious and struggling to breathe with audible wheezing, nasal flaring, and intercostal retractions after playing outside.",
    patientSummary: "6M, alert but anxious, audible wheezing, nasal flaring, intercostal retractions, SpO2 85%, history of asthma.",
    difficulty: "Intermediate",
    category: "Medical",
    certLevel: "EMT",
    imageUrl: "/images/scenario-pediatric.png",
    estimatedMinutes: 12,
    tags: ["pediatric", "respiratory", "asthma", "medical"],
    departureVideoUrl: "/videos/s2-departure.mp4",
  });

  await Promise.all([
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 1,
      phase: "Scene Safety",
      prompt: "You arrive at a residence for a child having difficulty breathing. What is your first action?",
      patientState: "You hear a child wheezing loudly from inside the house. The mother is at the door, waving you in urgently.",
      vitalSigns: null,
      correctActions: ["Don BSI/PPE and confirm scene safety before entering"],
      incorrectActions: [
        "Rush past the mother directly to the child",
        "Ask the mother to bring the child outside",
        "Call for fire department",
      ],
      feedbackCorrect: "Correct! Even in urgent pediatric calls, BSI and scene safety come first. Protect yourself so you can protect the patient.",
      feedbackIncorrect: "No matter how urgent the call sounds, always start with BSI/PPE and scene safety. This protects you and the patient.",
      hint: "What is always the first thing you do on any scene?",
      isCritical: false,
      videoUrl: "/videos/s2-step1-arrive-house.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 2,
      phase: "Scene Size-Up",
      prompt: "Scene is safe. You see one pediatric patient in respiratory distress. The mother reports a history of asthma. What additional resources do you request?",
      patientState: "6-year-old male sitting upright on the couch, audible wheezing, visible nasal flaring and intercostal retractions.",
      vitalSigns: null,
      correctActions: ["Call for ALS - pediatric patient in significant respiratory distress needs advanced interventions"],
      incorrectActions: [
        "No additional resources needed",
        "Call for hazmat",
        "Request police for crowd control",
      ],
      feedbackCorrect: "Excellent decision! A pediatric patient in significant respiratory distress benefits from ALS-level care, including nebulized medications.",
      feedbackIncorrect: "A 6-year-old with severe respiratory distress, retractions, and nasal flaring needs ALS resources. Paramedics can administer nebulized bronchodilators.",
      hint: "This child has signs of severe respiratory distress. Can BLS manage this alone, or would advanced interventions help?",
      isCritical: false,
      videoUrl: "/videos/s2-step2-enter-house.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 3,
      phase: "General Impression",
      prompt: "You approach the child. He is alert but unable to speak in full sentences, with audible wheezing. What is your immediate assessment?",
      patientState: "The child looks anxious, sitting in tripod position, nasal flaring with each breath. He can only say 1-2 words at a time between breaths.",
      vitalSigns: { hr: 140, rr: 36, spo2: 85, skinColor: "Pale", skinTemp: "Cool", skinMoisture: "Clammy" },
      correctActions: ["Patient is in respiratory distress - this is an immediate life threat requiring urgent intervention"],
      incorrectActions: [
        "Patient appears stable, proceed with normal assessment",
        "Patient is unresponsive, begin CPR",
        "No life threats identified",
      ],
      feedbackCorrect: "Correct! An SpO2 of 85%, inability to speak in full sentences, nasal flaring, and retractions indicate severe respiratory distress - a life threat.",
      feedbackIncorrect: "This child shows classic signs of severe respiratory distress: tripod positioning, nasal flaring, retractions, and an SpO2 of 85%. This IS a life threat.",
      hint: "Look at the SpO2, the breathing effort, and the child's ability to speak. Is this a life threat?",
      isCritical: true,
      videoUrl: "/videos/s2-step3-approach-child.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 4,
      phase: "Primary Assessment",
      prompt: "The child's airway is patent but severely compromised by bronchospasm. SpO2 is 85%. What is your breathing intervention?",
      patientState: "Wheezing throughout all lung fields. Intercostal and subcostal retractions. SpO2 85% on room air. The child is becoming more fatigued.",
      vitalSigns: { hr: 140, rr: 36, spo2: 85, skinColor: "Pale", skinTemp: "Cool", skinMoisture: "Clammy" },
      correctActions: ["Assist ventilations with BVM connected to high-flow supplemental oxygen at 15 LPM given the critically low SpO2"],
      incorrectActions: [
        "Apply nasal cannula at 2 LPM",
        "No oxygen needed, the child is breathing",
        "Withhold oxygen until ALS arrives",
      ],
      feedbackCorrect: "Excellent! With an SpO2 of 85% and increasing fatigue, BVM with high-flow O2 is appropriate to support this child's ventilations.",
      feedbackIncorrect: "An SpO2 of 85% is critically low. This child needs aggressive oxygen therapy. BVM with high-flow O2 at 15 LPM supports the inadequate ventilations.",
      hint: "The SpO2 is 85% and the child is tiring. What level of respiratory support does this require?",
      isCritical: true,
      videoUrl: "/videos/s2-step4-treat-breathing.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 5,
      phase: "Primary Assessment",
      prompt: "Circulation assessment shows pale, diaphoretic skin with poor capillary refill. How do you prioritize this patient?",
      patientState: "Skin is pale and clammy. Capillary refill is 4 seconds. The child is becoming less responsive to surroundings.",
      vitalSigns: { hr: 148, rr: 36, spo2: 85, skinColor: "Pale", skinTemp: "Cool", skinMoisture: "Diaphoretic" },
      correctActions: ["This is a HIGH priority patient - prepare for immediate transport, continue ventilatory support en route"],
      incorrectActions: [
        "Low priority, wait for ALS on scene",
        "Continue extended assessment on scene",
        "The circulation is normal for a child this age",
      ],
      feedbackCorrect: "Correct! Poor perfusion signs in a pediatric patient with respiratory failure demands immediate transport with continued care en route.",
      feedbackIncorrect: "Pale, diaphoretic skin with delayed capillary refill in a child with an SpO2 of 85% means this is a critical patient. Do not delay transport.",
      hint: "Combine the respiratory distress with the circulation findings. How sick is this child?",
      isCritical: true,
      videoUrl: "/videos/s2-step5-prepare-transport.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 6,
      phase: "Transport",
      prompt: "You decide to transport. What do you plan for the patient history gathering?",
      patientState: "Patient loaded onto stretcher with BVM ventilations continuing. Mother riding along.",
      vitalSigns: { hr: 140, rr: 28, spo2: 89, skinColor: "Pale", skinTemp: "Cool", skinMoisture: "Diaphoretic" },
      correctActions: ["Gather SAMPLE/OPQRST history en route since the patient is unstable and should not be delayed on scene"],
      incorrectActions: [
        "Stay on scene to complete a full history before transport",
        "Skip the history entirely",
        "Wait until arriving at the hospital to ask questions",
      ],
      feedbackCorrect: "Correct! For unstable patients, gather history en route. Don't delay transport for information you can collect in the ambulance.",
      feedbackIncorrect: "Never delay transport of an unstable patient for on-scene history. Gather SAMPLE and OPQRST en route to the hospital.",
      hint: "Should you stay on scene for a full workup with an unstable pediatric patient?",
      isCritical: false,
      videoUrl: "/videos/s2-step6-in-ambulance.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 7,
      phase: "Reassessment",
      prompt: "En route, what should you reassess on this critical patient?",
      patientState: "You are in the ambulance heading to the hospital. The child appears slightly improved with assisted ventilations.",
      vitalSigns: { hr: 136, rr: 28, spo2: 91, bp: "88/56", skinColor: "Pale", skinTemp: "Cool", skinMoisture: "Less diaphoretic" },
      correctActions: ["Recheck full vital signs including BP, HR, RR, SpO2, and EtCO2. Continue monitoring airway and breathing closely"],
      incorrectActions: [
        "No need to recheck, patient seems better",
        "Only check pulse",
        "Remove the oxygen since SpO2 improved slightly",
      ],
      feedbackCorrect: "Excellent! Frequent reassessment of vitals is critical for unstable patients. The slight improvement is promising but this patient remains critical.",
      feedbackIncorrect: "Critical patients need frequent, complete reassessments. Never assume improvement means the patient is stable. Continue monitoring all vitals.",
      hint: "How often should you reassess an unstable patient? What vitals do you need?",
      isCritical: false,
      videoUrl: "/videos/s2-step6-in-ambulance.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 8,
      phase: "Transfer",
      prompt: "You arrive at the hospital. What is your final action?",
      patientState: "Arriving at the emergency department. Hospital staff is ready to receive the patient.",
      vitalSigns: { hr: 130, rr: 24, spo2: 92, bp: "90/58" },
      correctActions: ["Transfer care to hospital staff with a complete verbal report of findings, interventions, and patient response"],
      incorrectActions: [
        "Leave the patient on the stretcher and walk away",
        "Hand the patient off without any verbal report",
        "Continue treating the patient in the ER yourself",
      ],
      feedbackCorrect: "Perfect! A complete, organized handoff report ensures continuity of care. Include patient info, chief complaint, findings, interventions, and responses.",
      feedbackIncorrect: "Always provide a complete verbal report when transferring care. The hospital team needs to know what happened, what you found, and what you did.",
      hint: "What information does the hospital team need to continue caring for this patient?",
      isCritical: false,
      videoUrl: "/videos/s2-step7-arrive-hospital.mp4",
    }),
  ]);

  const scenario3 = await storage.createScenario({
    title: "Respiratory Failure - Elderly Patient",
    description: "A 72-year-old male is found unresponsive in bed with snoring respirations, extremely low oxygen saturation, and weak pulse. Requires immediate airway management.",
    patientSummary: "72M, unresponsive, snoring respirations, RR 4, SpO2 70%, HR 52, cyanotic.",
    difficulty: "Advanced",
    category: "Medical",
    certLevel: "EMT",
    imageUrl: "/images/scenario-elderly.png",
    estimatedMinutes: 10,
    tags: ["respiratory failure", "BVM", "airway management", "geriatric"],
    departureVideoUrl: "/videos/s3-departure.mp4",
  });

  await Promise.all([
    storage.createScenarioStep({
      scenarioId: scenario3.id,
      stepOrder: 1,
      phase: "Scene Safety",
      prompt: "You respond to a residence for an unresponsive male. What is your first action upon arrival?",
      patientState: "Family member meets you at the door, very distressed. 'He won't wake up! Please hurry!'",
      vitalSigns: null,
      correctActions: ["Don BSI/PPE including gloves, mask, and eye protection, then confirm scene safety"],
      incorrectActions: [
        "Rush to the patient's bedside immediately",
        "Ask the family what medications he takes",
        "Call for helicopter transport",
      ],
      feedbackCorrect: "Correct! Even in critical situations, BSI/PPE comes first. Eye protection is especially important when managing airways.",
      feedbackIncorrect: "Always don PPE first, including eye protection for airway management cases. Scene safety is non-negotiable.",
      hint: "What PPE is especially important when you may need to manage an airway?",
      isCritical: false,
      videoUrl: "/videos/s3-step1-arrive-house-night.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario3.id,
      stepOrder: 2,
      phase: "Scene Size-Up",
      prompt: "Scene is safe. One patient in bed, unresponsive. What resources do you request?",
      patientState: "72-year-old male lying in bed, cyanotic, snoring respirations audible from the doorway.",
      vitalSigns: null,
      correctActions: ["Call for ALS immediately - unresponsive patient with respiratory failure requires advanced airway management"],
      incorrectActions: [
        "No additional resources needed",
        "Call for police assistance",
        "Request fire department only",
      ],
      feedbackCorrect: "Excellent! An unresponsive patient with respiratory failure absolutely needs ALS for advanced airway management and medications.",
      feedbackIncorrect: "An unresponsive patient with signs of respiratory failure needs ALS. Paramedics can provide advanced airway management and medications.",
      hint: "Can BLS alone manage an unresponsive patient in respiratory failure?",
      isCritical: false,
      videoUrl: "/videos/s3-step2-enter-bedroom.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario3.id,
      stepOrder: 3,
      phase: "General Impression",
      prompt: "The patient is cyanotic with snoring respirations, groans only to painful stimuli. How do you assess his level of consciousness?",
      patientState: "Patient is lying supine, cyanotic lips and fingertips. Snoring with each breath. Only groans when you apply a sternal rub.",
      vitalSigns: { hr: 52, rr: 4, spo2: 70, bp: "92/58", skinColor: "Cyanotic", skinTemp: "Cool", skinMoisture: "Clammy" },
      correctActions: ["Patient responds to Pain only (P on AVPU). This is a critical, life-threatening emergency"],
      incorrectActions: [
        "Patient is Alert (A on AVPU)",
        "Patient is Unresponsive (U on AVPU)",
        "Patient responds to Verbal stimuli (V on AVPU)",
      ],
      feedbackCorrect: "Correct! Groaning to painful stimuli = Painful response (P) on AVPU. With an SpO2 of 70%, this is immediately life-threatening.",
      feedbackIncorrect: "The patient only responds to pain (groaning with sternal rub). He is not alert, doesn't respond to voice, and is not completely unresponsive. He is P on AVPU.",
      hint: "He doesn't respond to your voice but groans when you apply pain. Where does that fall on AVPU?",
      isCritical: true,
      videoUrl: "/videos/s3-step3-approach-bed.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario3.id,
      stepOrder: 4,
      phase: "Primary Assessment",
      prompt: "The patient has snoring respirations. How do you manage the airway?",
      patientState: "Loud snoring with each breath. The tongue appears to be partially obstructing the airway. RR is 4 breaths per minute.",
      vitalSigns: { hr: 52, rr: 4, spo2: 70, bp: "92/58", skinColor: "Cyanotic", skinTemp: "Cool", skinMoisture: "Clammy" },
      correctActions: ["Open airway with head-tilt chin-lift and insert an OPA (oropharyngeal airway) to maintain patency"],
      incorrectActions: [
        "The airway is fine, snoring is normal in sleep",
        "Place the patient on their stomach",
        "Insert a nasal cannula",
      ],
      feedbackCorrect: "Excellent! Snoring respirations indicate a partial airway obstruction. Head-tilt chin-lift opens it, and an OPA maintains it in an unresponsive patient.",
      feedbackIncorrect: "Snoring respirations mean the airway is partially obstructed, likely by the tongue. You must open it with a head-tilt chin-lift and maintain with an OPA.",
      hint: "What causes snoring respirations? How do you fix it and keep it open?",
      isCritical: true,
      videoUrl: "/videos/s3-step4-open-airway.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario3.id,
      stepOrder: 5,
      phase: "Primary Assessment",
      prompt: "Airway is now open with OPA in place. RR is 4, SpO2 is 70%. The breathing is clearly inadequate. What is your intervention?",
      patientState: "With OPA in place, snoring has stopped. However, respirations remain at 4/min and very shallow. SpO2 remains critically low at 70%.",
      vitalSigns: { hr: 52, rr: 4, spo2: 70, bp: "92/58", skinColor: "Cyanotic", skinTemp: "Cool", skinMoisture: "Clammy" },
      correctActions: ["Begin assisted ventilations with BVM connected to high-flow oxygen at 15 LPM - respirations are inadequate"],
      incorrectActions: [
        "Apply non-rebreather mask at 15 LPM",
        "Apply nasal cannula at 6 LPM",
        "Wait for ALS before providing ventilatory support",
      ],
      feedbackCorrect: "Perfect! A respiratory rate of 4 is grossly inadequate. BVM ventilations with high-flow O2 is the only appropriate intervention here.",
      feedbackIncorrect: "A respiratory rate of 4 means the patient is barely breathing. Passive oxygen (NRB, nasal cannula) is not enough. You must actively ventilate with a BVM.",
      hint: "Is a respiratory rate of 4 adequate? Can passive oxygen delivery fix an SpO2 of 70% at this rate?",
      isCritical: true,
      videoUrl: "/videos/s3-step5-bvm-ventilate.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario3.id,
      stepOrder: 6,
      phase: "Reassessment",
      prompt: "After 2 minutes of BVM ventilations with O2, you reassess. SpO2 has risen to 86%, HR to 66. Skin color improving slightly. Patient begins to move arms. What do you do?",
      patientState: "With continued BVM ventilations, the patient's color is slowly improving. He begins moving his arms slightly but remains non-verbal.",
      vitalSigns: { hr: 66, rr: 8, spo2: 86, bp: "98/62", skinColor: "Less cyanotic", skinTemp: "Cool", skinMoisture: "Clammy" },
      correctActions: ["Continue BVM ventilations - SpO2 is improving but still below normal. Monitor for increased consciousness and prepare for potential OPA removal if gag reflex returns"],
      incorrectActions: [
        "Stop BVM ventilations since SpO2 improved",
        "Remove the OPA since the patient is moving",
        "Downgrade to nasal cannula since he's getting better",
      ],
      feedbackCorrect: "Correct! The improvement is encouraging but SpO2 is still low. Continue BVM. Watch for gag reflex return as consciousness improves.",
      feedbackIncorrect: "An SpO2 of 86% is still dangerously low. Continue BVM ventilations. Don't remove the OPA unless the patient develops a gag reflex.",
      hint: "Is 86% a normal SpO2? Should you stop an intervention that's working just because there's some improvement?",
      isCritical: true,
      videoUrl: "/videos/s3-step6-reassess.mp4",
    }),
  ]);

  const scenario4 = await storage.createScenario({
    title: "Motor Vehicle Collision",
    description: "Respond to a two-vehicle collision on a suburban road. One patient is trapped with multiple injuries. Perform a systematic trauma assessment.",
    patientSummary: "35M, restrained driver, airbag deployed, complaining of chest and neck pain, possible entrapment.",
    difficulty: "Intermediate",
    category: "Trauma",
    certLevel: "EMT",
    imageUrl: "/images/scenario-assessment.png",
    estimatedMinutes: 12,
    tags: ["trauma", "MVC", "spinal", "extrication"],
    departureVideoUrl: "/videos/s4-departure.mp4",
  });

  await Promise.all([
    storage.createScenarioStep({
      scenarioId: scenario4.id,
      stepOrder: 1,
      phase: "Scene Safety",
      prompt: "You arrive at a two-vehicle collision on a suburban road. What are your first actions?",
      patientState: "Two vehicles with front-end damage on a two-lane road. Fluids leaking from one vehicle. Traffic passing slowly.",
      vitalSigns: null,
      correctActions: ["Don BSI/PPE, assess scene safety including traffic hazards, fluid leaks, and vehicle stability"],
      incorrectActions: [
        "Rush to the nearest vehicle to check patients",
        "Direct traffic yourself without PPE",
        "Begin extrication immediately",
      ],
      feedbackCorrect: "Correct! MVC scenes have multiple hazards: traffic, leaking fluids, unstable vehicles, broken glass. Scene safety is critical.",
      feedbackIncorrect: "MVC scenes are among the most dangerous. Assess for traffic hazards, leaking fluids, vehicle stability, and downed power lines before approaching.",
      hint: "What hazards are unique to motor vehicle collision scenes?",
      isCritical: false,
      videoUrl: "/videos/s4-step1-arrive-mvc.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario4.id,
      stepOrder: 2,
      phase: "Scene Size-Up",
      prompt: "Two vehicles, two potential patients. The second vehicle's occupant is ambulatory and appears uninjured. What resources do you need?",
      patientState: "Vehicle 1: driver pinned by dashboard, conscious, in pain. Vehicle 2: driver standing outside, appears uninjured.",
      vitalSigns: null,
      correctActions: ["Call for fire/rescue for extrication, request additional ambulance for second patient, consider ALS for the trapped patient"],
      incorrectActions: [
        "No additional resources needed",
        "Only request police for traffic control",
        "Tell the ambulatory patient to drive themselves to the hospital",
      ],
      feedbackCorrect: "Good thinking! Entrapped patients need fire/rescue. Every patient at an MVC needs evaluation, even if they appear uninjured.",
      feedbackIncorrect: "A trapped patient requires fire/rescue for extrication. You need additional resources, and the second patient must also be evaluated.",
      hint: "One patient is trapped. Can you extricate them? Does the other patient need evaluation?",
      isCritical: false,
      videoUrl: "/videos/s4-step2-approach-vehicles.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario4.id,
      stepOrder: 3,
      phase: "General Impression",
      prompt: "You reach the trapped driver. He is alert, restrained, airbag deployed. He complains of chest and neck pain. What's your immediate concern?",
      patientState: "35-year-old male, seatbelt on, airbag deployed. Steering wheel deformed. Complaints of neck and chest pain. Dashboard pressing on his legs.",
      vitalSigns: { hr: 108, rr: 22, spo2: 95, bp: "128/82" },
      correctActions: ["Manually stabilize the cervical spine - mechanism and symptoms suggest potential spinal injury"],
      incorrectActions: [
        "No spinal precautions needed since he's conscious",
        "Wait for extrication before any assessment",
        "Pull the patient from the vehicle immediately",
      ],
      feedbackCorrect: "Excellent! High-speed MVC with neck pain is a classic indication for spinal precautions. Manual c-spine stabilization should begin immediately.",
      feedbackIncorrect: "A high-speed MVC with neck pain requires immediate manual cervical spine stabilization. Never move a trauma patient without protecting the spine first.",
      hint: "What does neck pain after a high-speed collision tell you about spinal injury risk?",
      isCritical: true,
      videoUrl: "/videos/s4-step3-look-in-car.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario4.id,
      stepOrder: 4,
      phase: "Primary Assessment",
      prompt: "With c-spine stabilized, you assess the airway and breathing. The patient is speaking clearly, RR 22, SpO2 95%. He has tenderness over the left chest wall. What do you do?",
      patientState: "Patient speaking in full sentences. Left chest wall tender to palpation. Equal chest rise bilaterally. Breath sounds slightly diminished on the left.",
      vitalSigns: { hr: 108, rr: 22, spo2: 95, bp: "128/82", skinColor: "Pink", skinTemp: "Warm", skinMoisture: "Dry" },
      correctActions: ["Airway patent. Apply high-flow oxygen via non-rebreather at 15 LPM as a precaution for potential chest injury. Monitor for deterioration"],
      incorrectActions: [
        "No oxygen needed, SpO2 is 95%",
        "Begin CPR",
        "Insert an OPA",
      ],
      feedbackCorrect: "Correct! With possible chest wall injury and diminished breath sounds, prophylactic high-flow O2 is appropriate. Monitor closely for deterioration.",
      feedbackIncorrect: "Chest wall tenderness with diminished breath sounds suggests possible rib fractures or pneumothorax. High-flow O2 and close monitoring are essential.",
      hint: "What could cause diminished breath sounds on one side after blunt chest trauma?",
      isCritical: false,
      videoUrl: "/videos/s4-step4-stabilize-cspine.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario4.id,
      stepOrder: 5,
      phase: "Primary Assessment",
      prompt: "Circulation assessment: pulse 108, BP 128/82, skin warm and dry. No external hemorrhage visible. How do you prioritize this patient?",
      patientState: "Vitals relatively stable. Patient is alert and oriented. Still complaining of neck and chest pain. Remains trapped.",
      vitalSigns: { hr: 108, rr: 22, spo2: 95, bp: "128/82", skinColor: "Pink", skinTemp: "Warm", skinMoisture: "Dry" },
      correctActions: ["HIGH priority patient due to mechanism, entrapment, neck pain, and possible chest injury. Expedite extrication and transport"],
      incorrectActions: [
        "Low priority since vitals are stable",
        "Delayed priority, treat other patients first",
        "No priority needed, he can wait for extrication",
      ],
      feedbackCorrect: "Correct! Despite relatively stable vitals, the mechanism, entrapment, spinal concerns, and chest injury make this a high priority patient.",
      feedbackIncorrect: "Stable vitals don't mean low priority. The mechanism of injury, entrapment, neck pain, and possible chest injury all point to high priority.",
      hint: "Should you base priority only on current vitals, or also consider the mechanism and potential injuries?",
      isCritical: true,
      videoUrl: "/videos/s4-step5-assess-trapped.mp4",
    }),
  ]);

  const scenario5 = await storage.createScenario({
    title: "Cardiac Arrest - Witnessed",
    description: "A 58-year-old male collapses at a restaurant. Bystanders report he was eating, suddenly clutched his chest, and fell from his chair. He is now unresponsive.",
    patientSummary: "58M, witnessed collapse, unresponsive, no pulse, no breathing.",
    difficulty: "Advanced",
    category: "Medical",
    certLevel: "EMT",
    imageUrl: "/images/scenario-ambulance-interior.png",
    estimatedMinutes: 10,
    tags: ["cardiac arrest", "CPR", "AED", "BLS"],
    departureVideoUrl: "/videos/s5-departure.mp4",
  });

  await Promise.all([
    storage.createScenarioStep({
      scenarioId: scenario5.id,
      stepOrder: 1,
      phase: "Scene Safety",
      prompt: "You arrive at a restaurant for an unresponsive male. The scene is chaotic with bystanders surrounding the patient. What do you do first?",
      patientState: "A man is lying on the floor between tables. A crowd of 15-20 people surrounds him. One bystander is yelling for help.",
      vitalSigns: null,
      correctActions: ["Don BSI/PPE, confirm scene safety, and direct bystanders to clear space for you to work"],
      incorrectActions: [
        "Begin chest compressions immediately without PPE",
        "Ask bystanders what happened before approaching",
        "Call for police to manage the crowd first",
      ],
      feedbackCorrect: "Correct! PPE first, then clear the scene so you have space to work. In cardiac arrest, every second counts, but you still need PPE.",
      feedbackIncorrect: "Even in cardiac arrest, you need PPE. Get gloves on quickly, clear space, and then begin your assessment. It only takes seconds.",
      hint: "Can you do effective CPR in a crowd without PPE?",
      isCritical: false,
      videoUrl: "/videos/s5-step1-arrive-restaurant.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario5.id,
      stepOrder: 2,
      phase: "General Impression",
      prompt: "You reach the patient. He is supine, motionless, cyanotic. You shake his shoulders and shout - no response. What is your immediate assessment?",
      patientState: "58-year-old male, supine on restaurant floor. Not moving, not breathing, cyanotic. No response to shoulder tap and verbal stimulation.",
      vitalSigns: null,
      correctActions: ["Patient is Unresponsive (U on AVPU). Check for a pulse immediately - this may be cardiac arrest"],
      incorrectActions: [
        "Patient is responding to pain, continue talking to him",
        "Place the patient in the recovery position",
        "Begin a detailed head-to-toe exam",
      ],
      feedbackCorrect: "Correct! No response to stimulation = Unresponsive. Immediately check for pulse to confirm cardiac arrest.",
      feedbackIncorrect: "No response to shoulder tap or voice = Unresponsive (U on AVPU). With no breathing and cyanosis, immediately check for pulse.",
      hint: "No response to stimulation, not breathing, cyanotic. What life-threatening condition does this suggest?",
      isCritical: true,
      videoUrl: "/videos/s5-step2-enter-restaurant.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario5.id,
      stepOrder: 3,
      phase: "Primary Assessment",
      prompt: "You check the carotid pulse for 10 seconds - no pulse detected. No breathing observed. What do you do?",
      patientState: "No pulse. No respiratory effort. Patient is in cardiac arrest.",
      vitalSigns: null,
      correctActions: ["Begin high-quality CPR immediately: 30 compressions to 2 ventilations, apply AED as soon as available"],
      incorrectActions: [
        "Check for a pulse again to be sure",
        "Begin rescue breathing only",
        "Wait for ALS to arrive before starting CPR",
      ],
      feedbackCorrect: "Perfect! In cardiac arrest, begin CPR immediately. High-quality compressions (hard, fast, full recoil) with early defibrillation save lives.",
      feedbackIncorrect: "No pulse, no breathing = cardiac arrest. Begin CPR immediately. Every minute without CPR decreases survival by 7-10%.",
      hint: "What is the definitive treatment for cardiac arrest at the BLS level?",
      isCritical: true,
      videoUrl: "/videos/s5-step3-kneel-cpr.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario5.id,
      stepOrder: 4,
      phase: "Primary Assessment",
      prompt: "CPR is in progress. Your partner brings the AED. What are the correct steps?",
      patientState: "CPR in progress. Partner arrives with AED and additional equipment.",
      vitalSigns: null,
      correctActions: ["Power on AED, apply pads, stop CPR for analysis, follow AED prompts for shock if advised, then immediately resume CPR"],
      incorrectActions: [
        "Continue CPR and skip the AED",
        "Apply the AED pads but don't stop CPR for analysis",
        "Only apply the AED if the patient doesn't improve with CPR alone",
      ],
      feedbackCorrect: "Excellent! Early defibrillation is critical. Apply pads, allow analysis, deliver shock if advised, and immediately resume CPR after the shock.",
      feedbackIncorrect: "The AED is the most important intervention in cardiac arrest. Apply it as soon as available, follow its prompts, and resume CPR immediately after any shock.",
      hint: "In witnessed cardiac arrest, what single intervention has the greatest impact on survival?",
      isCritical: true,
      videoUrl: "/videos/s5-step4-apply-aed.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario5.id,
      stepOrder: 5,
      phase: "Reassessment",
      prompt: "AED delivered one shock. You've resumed CPR. After 2 minutes of CPR, what should you do?",
      patientState: "Two minutes since last AED analysis. CPR has been continuous with good quality compressions.",
      vitalSigns: null,
      correctActions: ["Pause CPR briefly for AED reanalysis. Check pulse. Switch compressors to prevent fatigue. Resume CPR immediately after analysis"],
      incorrectActions: [
        "Continue CPR without pausing for another 5 minutes",
        "Stop CPR and check for breathing only",
        "Remove AED pads since one shock was already delivered",
      ],
      feedbackCorrect: "Correct! Every 2 minutes: reanalyze with AED, check pulse, switch compressors. Compressor fatigue reduces CPR quality.",
      feedbackIncorrect: "The resuscitation cycle is 2 minutes of CPR, then pause for AED reanalysis, pulse check, and compressor switch. This ensures quality and checks for ROSC.",
      hint: "How often should you reanalyze, check pulse, and switch compressors during CPR?",
      isCritical: true,
      videoUrl: "/videos/s5-step5-continue-cpr.mp4",
    }),
  ]);

  log("Database seeded with 5 scenarios", "seed");
}
