import { storage } from "./storage";
import { db } from "./db";
import { scenarios, scenarioSteps, attempts } from "@shared/schema";
import { eq, and, sql } from "drizzle-orm";
import { log } from "./index";

async function scenarioExists(title: string): Promise<boolean> {
  const existing = await db.select().from(scenarios).where(eq(scenarios.title, title)).limit(1);
  return existing.length > 0;
}

async function getScenarioByTitle(title: string) {
  const [scenario] = await db.select().from(scenarios).where(eq(scenarios.title, title)).limit(1);
  return scenario ?? null;
}

async function getStepCount(scenarioId: string): Promise<number> {
  const [result] = await db.select({ count: sql<number>`count(*)::int` }).from(scenarioSteps).where(eq(scenarioSteps.scenarioId, scenarioId));
  return result?.count ?? 0;
}

async function deleteScenarioData(scenarioId: string) {
  await db.delete(attempts).where(eq(attempts.scenarioId, scenarioId));
  await db.delete(scenarioSteps).where(eq(scenarioSteps.scenarioId, scenarioId));
  await db.delete(scenarios).where(eq(scenarios.id, scenarioId));
}

export async function seedDatabase() {
  let seededCount = 0;

  const existingS1 = await getScenarioByTitle("Sports Injury - Primary Assessment");
  if (existingS1) {
    const stepCount = await getStepCount(existingS1.id);
    if (stepCount !== 6) {
      log(`Scenario 1 has ${stepCount} steps (expected 6), re-seeding Scenario 1...`, "seed");
      await deleteScenarioData(existingS1.id);
      await seedScenario1Only();
      seededCount += 1;
    }
  } else {
    log("Seeding EMS scenarios...", "seed");
    await seedEMSScenarios();
    seededCount += 5;
  }

  if (!(await scenarioExists("Acute Stroke - CVA Recognition"))) {
    log("Seeding Nursing scenarios...", "seed");
    await seedNursingScenario();
    seededCount += 1;
  }

  if (seededCount === 0) {
    log("Database already seeded", "seed");
  } else {
    log(`Seeded ${seededCount} new scenarios`, "seed");
  }
}

async function seedScenario1Only() {
  await createScenario1WithSteps();
}

async function createScenario1WithSteps() {
  const scenario1 = await storage.createScenario({
    title: "Sports Injury - Primary Assessment",
    description: "A 22-year-old female is sitting on the ground holding her left side and breathing rapidly after falling during a soccer game. Her teammates report she was struck in the ribs by another player's elbow. Perform a complete primary assessment following proper EMS protocol.",
    patientSummary: "22F soccer player, sitting on ground clutching left side, rapid shallow breathing, blunt trauma from elbow strike to ribs during game. Teammates on scene.",
    difficulty: "Beginner",
    category: "Trauma",
    certLevel: "EMT",
    imageUrl: "/images/scenario-sports-injury.png",
    estimatedMinutes: 20,
    tags: ["trauma", "rib injury", "primary assessment", "scene safety", "BSI", "AVPU", "shock"],
    departureVideoUrl: "/videos/s1-departure.mp4",
  });

  await Promise.all([
    storage.createScenarioStep({
      scenarioId: scenario1.id,
      stepOrder: 1,
      phase: "BSI / PPE",
      prompt: "You are dispatched to a local soccer field for a player down with a possible rib injury. You are seated in the back of the ambulance approaching the scene. What is your very first action before exiting the rig?",
      patientState: "You are in the back of the ambulance. Equipment bags, oxygen cylinder, and stretcher are visible around you. The ambulance is slowing to a stop.",
      vitalSigns: null,
      correctActions: ["Don appropriate BSI/PPE - put on nitrile gloves before exiting the ambulance"],
      incorrectActions: [
        "Grab your jump bag and exit the rig quickly while putting gloves on as you walk to the patient",
        "Radio dispatch to confirm the exact location on the field, then don PPE while waiting for their response",
        "Skip gloves for now since this is a sports injury with no visible blood - you can glove up after your initial assessment",
      ],
      feedbackCorrect: "Correct! BSI always comes first. You've donned your nitrile gloves. You are now protected and ready to exit the rig and approach the scene.",
      feedbackIncorrect: "BSI/PPE is always your very first action - before you leave the ambulance, before you approach the patient, before anything else. Put on your gloves.",
      hint: "What do you always do FIRST at every single scene before anything else?",
      isCritical: false,
      videoUrl: "/videos/s1-step1-ppe.mp4",
      questions: null,
    }),
    storage.createScenarioStep({
      scenarioId: scenario1.id,
      stepOrder: 2,
      phase: "Scene Size-Up",
      prompt: "",
      patientState: null,
      vitalSigns: null,
      correctActions: [],
      incorrectActions: [],
      feedbackCorrect: "",
      feedbackIncorrect: "",
      hint: null,
      isCritical: false,
      videoUrl: "/videos/s1-step2-scene-approach.mp4",
      questions: [
        {
          prompt: "You step out of the ambulance with your PPE on. You can see a small grass soccer field ahead. A female player is on the ground about 50 yards away with teammates around her. What do you do before approaching?",
          patientState: "A small grass soccer field is visible. One player is sitting on the ground in the distance, surrounded by 3-4 teammates. The field appears clear with no ongoing play. No visible hazards.",
          vitalSigns: null,
          correctActions: ["Scan the scene and confirm it is safe - no traffic, no active play, no environmental hazards, no threats to your safety"],
          incorrectActions: [
            "Walk briskly toward the patient while scanning for hazards as you go",
            "Confirm scene safety by asking the bystanders near the ambulance if it's safe to approach",
            "Scan the scene for hazards, then radio dispatch to confirm the scene is safe before approaching",
          ],
          feedbackCorrect: "Good scene size-up. The scene is safe - no active play, no traffic, no hazards. You can now proceed toward the patient with your equipment.",
          feedbackIncorrect: "Always assess scene safety before approaching. Look for hazards: is there active play on the field? Traffic? Environmental dangers? Confirm the scene is safe before proceeding.",
          hint: "Is your scene safe? Look around before walking in.",
          isCritical: false,
        },
        {
          prompt: "Your scene is safe. As you walk across the field carrying your jump bag, you can see the player is conscious and in visible distress. Do you need to request any additional resources?",
          patientState: "Walking across the grass field toward the patient. She is sitting upright holding her left side. No other injuries visible on the field. Teammates are standing around her.",
          vitalSigns: null,
          correctActions: ["Consider calling for ALS based on initial impression - this is a judgment call. Requesting ALS intercept is appropriate for a trauma patient with respiratory distress"],
          incorrectActions: [
            "No additional resources needed at this time - complete your assessment first and request ALS only if the patient deteriorates",
            "Request a second BLS unit for additional manpower to carry equipment across the field",
            "Request ALS and also have dispatch send fire department for a possible extrication assist",
          ],
          feedbackCorrect: "Good judgment. Calling for ALS is a reasonable decision for a trauma patient showing respiratory distress. Paramedics can provide pain management and advanced assessment if needed.",
          feedbackIncorrect: "Consider the resources you might need. For a trauma patient showing signs of respiratory distress, requesting ALS backup is a prudent judgment call. Specialized teams like hazmat or extrication are not needed here.",
          hint: "Based on what you can see from a distance, might this patient benefit from ALS-level care?",
          isCritical: false,
        },
      ],
    }),
    storage.createScenarioStep({
      scenarioId: scenario1.id,
      stepOrder: 3,
      phase: "Scene Size-Up",
      prompt: "",
      patientState: null,
      vitalSigns: null,
      correctActions: [],
      incorrectActions: [],
      feedbackCorrect: "",
      feedbackIncorrect: "",
      hint: null,
      isCritical: false,
      videoUrl: "/videos/s1-step3-patient-contact.mp4",
      questions: [
        {
          prompt: "You are now close to the patient. She is a 22-year-old female sitting on the ground, clutching her left side, and breathing hard. Her teammates are standing nearby. How many patients are on this scene?",
          patientState: "One female soccer player is sitting on the ground in obvious distress, clutching her left ribcage. She is grimacing with each breath. Three teammates stand around her looking worried. No one else appears injured.",
          vitalSigns: null,
          correctActions: ["There is 1 patient on this scene"],
          incorrectActions: [
            "There is 1 obvious patient, but you should assess each teammate individually to rule out injuries before committing to a single patient count",
            "There are potentially 2 patients - the player on the ground and the teammate who appears visibly shaken",
            "You cannot confirm the patient count until you perform a full assessment of the downed player and interview each bystander",
          ],
          feedbackCorrect: "Correct! There is 1 patient on this scene. The teammates are bystanders, not patients. You've correctly identified your single patient.",
          feedbackIncorrect: "Look at the scene carefully. Only one person is on the ground in distress. The teammates are standing and uninjured - they are bystanders. There is 1 patient.",
          hint: "How many people are actually injured here? Who is a patient and who is a bystander?",
          isCritical: false,
        },
        {
          prompt: "You kneel beside the patient. Her teammates tell you she was struck in the left ribs by another player's elbow and went down. Is this a mechanism of injury (MOI) or nature of illness (NOI)? What is the specific mechanism?",
          patientState: "The patient is a 22-year-old female sitting on the grass, clutching her left side. A teammate explains: 'She got elbowed hard in the ribs by another player and just dropped.'",
          vitalSigns: null,
          correctActions: ["This is a Mechanism of Injury (MOI). The specific MOI is blunt trauma - an elbow strike to the left ribcage"],
          incorrectActions: [
            "This is a Mechanism of Injury (MOI). The specific MOI is a fall with ground-level impact to the left side",
            "This could be either MOI or NOI - the respiratory distress could indicate an underlying medical condition triggered by exertion",
            "This is a Mechanism of Injury (MOI). The specific MOI is a twisting injury to the torso during athletic activity",
          ],
          feedbackCorrect: "Correct! This is a Mechanism of Injury. The specific MOI is blunt force trauma from an elbow strike to the left ribcage. This helps guide your assessment - you'll focus on the trauma site.",
          feedbackIncorrect: "The teammates describe a physical blow - an elbow to the ribs. This is a Mechanism of Injury (MOI), not a Nature of Illness. The specific mechanism is blunt trauma to the left ribcage from a direct strike.",
          hint: "Was this caused by a physical force (trauma) or a medical condition (illness)?",
          isCritical: false,
        },
        {
          prompt: "Based on the mechanism of injury - an elbow strike to the ribs during a soccer game - is there any indication for spinal motion restriction?",
          patientState: "The patient was struck in the ribs by an elbow while running. She did not fall and hit her head, was not tackled, and did not have a mechanism involving axial loading or significant deceleration. She is sitting up on her own.",
          vitalSigns: null,
          correctActions: ["No indication for spinal motion restriction. The MOI was an isolated elbow strike to the ribs - no axial loading, no head/neck involvement, no loss of consciousness"],
          incorrectActions: [
            "Apply spinal motion restriction as a precaution - any trauma patient who fell to the ground should be immobilized",
            "Hold manual in-line stabilization while you assess for midline cervical tenderness before clearing the spine",
            "No spinal restriction needed, but apply a cervical collar for comfort and splinting of the upper torso",
          ],
          feedbackCorrect: "Correct! There is no indication for spinal motion restriction. The mechanism was a direct blow to the ribs - no head/neck involvement, no axial loading, no loss of consciousness, and the patient is sitting upright independently.",
          feedbackIncorrect: "Consider the mechanism: an elbow struck her ribs. There was no head or neck involvement, no fall from height, no axial loading, and no loss of consciousness. The patient is sitting upright. Spinal precautions are not indicated for this isolated mechanism.",
          hint: "Did the mechanism involve the head, neck, or spine? Was there axial loading or loss of consciousness?",
          isCritical: false,
        },
      ],
    }),
    storage.createScenarioStep({
      scenarioId: scenario1.id,
      stepOrder: 4,
      phase: "General Impression",
      prompt: "",
      patientState: null,
      vitalSigns: null,
      correctActions: [],
      incorrectActions: [],
      feedbackCorrect: "",
      feedbackIncorrect: "",
      hint: null,
      isCritical: false,
      videoUrl: "/videos/s1-step4-general-impression.mp4",
      questions: [
        {
          prompt: "You are now right next to the patient. Scan for any immediate life threats - major hemorrhage, obvious cardiac arrest, or severe airway compromise. What do you find?",
          patientState: "The patient is sitting upright, conscious, clutching her left side. No visible blood on her clothing or the ground. Her chest is rising and falling rapidly but she is breathing. She is alert and her eyes are open, tracking you.",
          vitalSigns: null,
          correctActions: ["There are no active life threats. No major hemorrhage, no cardiac arrest, no airway obstruction. The patient is conscious and breathing, though in distress"],
          incorrectActions: [
            "The rapid breathing and guarding suggest a potential tension pneumothorax - this is an immediate life threat requiring intervention",
            "No active life threats, but her pale skin and rapid breathing indicate she may decompensate quickly so begin CPR standby",
            "Possible internal hemorrhage from the rib injury constitutes an active life threat - apply direct pressure to the left ribcage",
          ],
          feedbackCorrect: "Correct! There are no immediate life threats. No major bleeding, the patient is not in arrest, and the airway is not obstructed. She is in pain and distress but has no immediately lethal conditions.",
          feedbackIncorrect: "Look carefully - there is no blood visible, the patient is conscious and breathing (not in arrest), and she is able to breathe (airway is not obstructed). There are no active life threats present.",
          hint: "Is there any major bleeding? Is the patient in cardiac arrest? Is the airway completely blocked?",
          isCritical: false,
        },
        {
          prompt: "Assess the patient's level of responsiveness using the AVPU scale. You make eye contact and say 'Hi, I'm an EMT, can you tell me what happened?' She looks at you and says through gritted teeth: 'I got hit... in my ribs... it really hurts.' What is her AVPU level?",
          patientState: "The patient makes direct eye contact when you speak. She responds verbally, telling you what happened in short phrases between painful breaths. She is oriented and aware of her surroundings.",
          vitalSigns: null,
          correctActions: ["The patient is Alert (A on AVPU). She is awake, makes eye contact, responds verbally, and is oriented to her surroundings"],
          incorrectActions: [
            "The patient is Verbal (V) - she only responded after you initiated verbal contact and introduced yourself",
            "The patient is Alert (A) but with altered mental status - her short fragmented sentences suggest decreased responsiveness",
            "The patient is between Alert and Verbal (A/V) - she is awake but her pain-limited speech suggests she is not fully alert",
          ],
          feedbackCorrect: "Correct! The patient is Alert (A on AVPU). She is awake and oriented - she makes eye contact, speaks to you, and describes what happened. Being in pain does not change the AVPU level.",
          feedbackIncorrect: "The patient is Alert (A). She was already awake and aware before you spoke - she makes eye contact, talks to you, and is oriented. 'Verbal' would mean she only responds when spoken to. 'Pain' means she only responds to painful stimuli. Being in pain is not the same as 'responds to Pain' on AVPU.",
          hint: "Was the patient already awake and aware before you spoke, or did she only respond after you spoke or applied a stimulus?",
          isCritical: false,
        },
        {
          prompt: "Begin your primary assessment. Evaluate the patient's airway. She is speaking to you in short sentences between winces of pain. Her voice is clear with no gurgling, stridor, or obstruction sounds. What are your findings?",
          patientState: "The patient speaks in short, clear sentences interrupted by pain. 'It hurts... when I breathe... the left side.' No gurgling, stridor, snoring, or signs of foreign body obstruction. Her mouth and throat are clear.",
          vitalSigns: null,
          correctActions: ["The airway is patent. The patient is speaking clearly, indicating an open airway. No interventions needed at this time"],
          incorrectActions: [
            "The airway is patent but at risk - insert a nasopharyngeal airway (NPA) as a precaution in case she deteriorates",
            "The airway is patent now but position the patient supine with a head-tilt chin-lift to ensure it stays open",
            "The airway appears patent but her short sentences between pain suggest partial obstruction - apply jaw thrust and reassess",
          ],
          feedbackCorrect: "Correct! The airway is patent. A patient who can speak clearly has an open airway. No airway interventions are needed at this time.",
          feedbackIncorrect: "The patient is speaking to you clearly. If the patient can speak, the airway is open (patent). No interventions such as suctioning, OPA, or head-tilt chin-lift are indicated for a patent airway.",
          hint: "Can the patient speak? What does the ability to speak tell you about the airway?",
          isCritical: false,
        },
      ],
    }),
    storage.createScenarioStep({
      scenarioId: scenario1.id,
      stepOrder: 5,
      phase: "Primary Assessment",
      prompt: "",
      patientState: null,
      vitalSigns: null,
      correctActions: [],
      incorrectActions: [],
      feedbackCorrect: "",
      feedbackIncorrect: "",
      hint: null,
      isCritical: true,
      videoUrl: "/videos/s1-step5-breathing.mp4",
      questions: [
        {
          prompt: "Evaluate breathing. You place your stethoscope on the patient's chest. She is breathing rapidly and shallowly, guarding her left side with each breath. Your assessment reveals: respiratory rate 32 breaths per minute, SpO2 88%, diminished breath sounds on the left side. What is your assessment and intervention?",
          patientState: "Rapid, shallow breathing at 32/min. She winces and guards her left ribs with every breath. Pulse oximeter reads 88%. Breath sounds are diminished on the left side where the impact occurred. Right lung sounds are clear.",
          vitalSigns: { hr: 124, rr: 32, spo2: 88, skinColor: "Pale", skinTemp: "Cool", skinMoisture: "Diaphoretic" },
          correctActions: ["Breathing is rapid and shallow at 32/min with an SpO2 of 88%. This is inadequate breathing requiring intervention. Administer high-flow oxygen via non-rebreather mask at 15 liters per minute"],
          incorrectActions: [
            "Breathing is rapid but she is ventilating on her own - apply a nasal cannula at 6 LPM and reassess in 5 minutes",
            "The SpO2 of 88% indicates she is not ventilating adequately - assist ventilations immediately with a bag-valve mask at 12 breaths per minute",
            "Apply a non-rebreather mask at 10 LPM - 15 LPM is only indicated if the SpO2 drops below 85%",
          ],
          feedbackCorrect: "Excellent! With a respiratory rate of 32, SpO2 of 88%, and diminished left-side breath sounds, this patient needs high-flow oxygen immediately. A non-rebreather mask at 15 LPM is the correct BLS intervention for this level of hypoxia.",
          feedbackIncorrect: "A respiratory rate of 32, SpO2 of 88%, and diminished breath sounds indicate significant respiratory compromise. The patient needs high-flow oxygen via non-rebreather mask at 15 LPM. A nasal cannula is insufficient for this degree of hypoxia, and BVM ventilations are not indicated for a patient who is breathing on their own.",
          hint: "The SpO2 is 88% and she's breathing fast and shallow. What oxygen delivery device provides the highest concentration at the BLS level?",
          isCritical: true,
        },
        {
          prompt: "With the non-rebreather mask now on the patient at 15 LPM, evaluate circulation. You check the radial pulse - it is rapid at 124 bpm and slightly weak. The skin is cool, pale, and diaphoretic (she is noticeably sweaty). Capillary refill is 3 seconds. No gross external bleeding visible. What do these findings indicate and what do you do?",
          patientState: "Non-rebreather mask is in place delivering 15 LPM O2. Radial pulse is rapid at 124 and slightly thready. Skin is cool, pale, and diaphoretic with visible sweat on her forehead and arms. Capillary refill is delayed at 3 seconds. No external bleeding anywhere.",
          vitalSigns: { hr: 124, rr: 32, spo2: 88, bp: "96/62", skinColor: "Pale", skinTemp: "Cool", skinMoisture: "Diaphoretic" },
          correctActions: ["Signs indicate possible shock: tachycardia (124), cool/pale/diaphoretic skin, delayed cap refill, hypotension (96/62). Continue NRB oxygen, maintain body temperature, and prepare for rapid transport"],
          incorrectActions: [
            "The tachycardia and diaphoresis are likely pain-related and exercise-related - continue monitoring but no immediate intervention beyond the oxygen already in place",
            "Signs of shock are present - elevate the patient's legs, start IV fluids, and apply a tourniquet to the left arm to maintain central perfusion",
            "Early shock is possible - position the patient flat on her back, apply oxygen via nasal cannula at 4 LPM, and perform a full secondary assessment before deciding on transport",
          ],
          feedbackCorrect: "Correct! A heart rate of 124, cool/pale/diaphoretic skin, delayed capillary refill, and a blood pressure of 96/62 are classic signs of compensated shock - likely from internal bleeding at the rib fracture site. Continue high-flow O2, apply a blanket for warmth, and prepare for rapid transport.",
          feedbackIncorrect: "Tachycardia (124), cool/pale/diaphoretic skin, delayed capillary refill (3 sec), and hypotension (96/62) are NOT normal. These are signs of compensated shock. The patient needs continued oxygen, a blanket for body temperature maintenance, and rapid transport to a trauma center.",
          hint: "What do a fast pulse, cool sweaty skin, and low blood pressure tell you when combined? What should you do to maintain body temperature in a shock patient?",
          isCritical: true,
        },
      ],
    }),
    storage.createScenarioStep({
      scenarioId: scenario1.id,
      stepOrder: 6,
      phase: "Transport Decision",
      prompt: "Based on your complete primary assessment - blunt trauma to ribs, rapid shallow breathing at 32/min, SpO2 88%, tachycardia at 124, signs of shock with cool/diaphoretic skin and hypotension - what is your transport priority for this patient?",
      patientState: "The patient is sitting up wearing the non-rebreather mask with a blanket draped over her. She is still in significant pain, breathing rapidly, and showing signs of shock. The stretcher is positioned beside her.",
      vitalSigns: { hr: 124, rr: 32, spo2: 88, bp: "96/62", skinColor: "Pale", skinTemp: "Cool", skinMoisture: "Diaphoretic" },
      correctActions: ["This is a HIGH priority patient. Load onto the stretcher immediately with the head elevated, maintain NRB oxygen, keep the blanket on, and initiate rapid transport to the closest appropriate trauma center"],
      incorrectActions: [
        "High priority - but hold on scene until ALS arrives for pain management and IV access before transporting",
        "Medium priority - the patient is conscious and talking, so complete a detailed secondary assessment on scene before loading for transport",
        "High priority - load immediately but transport to the nearest hospital emergency department rather than waiting for a trauma center",
      ],
      feedbackCorrect: "Excellent! This is a high-priority patient. She has signs of compensated shock from a significant rib injury with possible internal bleeding. Load her onto the stretcher, maintain oxygen, keep her warm, and transport rapidly to a trauma center. Do not delay on scene.",
      feedbackIncorrect: "A patient with tachycardia, hypotension, cool/diaphoretic skin, and respiratory compromise from a rib injury is NOT low priority. These are signs of shock suggesting possible internal bleeding. This is a HIGH priority patient requiring immediate transport.",
      hint: "What do all the vital signs and clinical findings together tell you about this patient's priority level?",
      isCritical: true,
      videoUrl: "/videos/s1-step7-transport.mp4",
      questions: null,
    }),
  ]);
}

async function seedEMSScenarios() {
  await createScenario1WithSteps();

  const scenario2 = await storage.createScenario({
    title: "Severe Asthma Attack",
    description: "Respond to a residence where a 28-year-old male named Marcus is in severe respiratory distress from an acute asthma exacerbation. His girlfriend Jenna reports he was exercising outside when the attack began and it has been getting worse for the past 20 minutes. Perform a systematic assessment and provide emergency treatment.",
    patientSummary: "28M 'Marcus', severe respiratory distress, tripod position, audible wheezing, nasal flaring, intercostal retractions, pale/diaphoretic, unable to speak full sentences. History of asthma. Girlfriend Jenna on scene.",
    difficulty: "Intermediate",
    category: "Medical",
    certLevel: "EMT",
    imageUrl: "/images/scenario-asthma.png",
    estimatedMinutes: 15,
    tags: ["respiratory", "asthma", "medical", "inhaler", "oxygen", "adult"],
    departureVideoUrl: "/videos/s2-departure.mp4",
  });

  await Promise.all([
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 1,
      phase: "Scene Safety",
      prompt: "You walk into the suburban home. The living room is clean and well-lit with natural daylight. What are your first actions before approaching the patient?",
      patientState: "You can hear audible wheezing from the living room as you enter. The girlfriend Jenna is standing near the sofa, waving you in urgently.",
      vitalSigns: null,
      correctActions: ["Don BSI/PPE (surgical mask and nitrile gloves), then visually scan the scene to confirm it is safe"],
      incorrectActions: [
        "Rush directly to the patient without PPE",
        "Ask the girlfriend to describe what happened before putting on gloves",
        "Call for fire department backup first",
      ],
      feedbackCorrect: "Correct! BSI/PPE is on. Scene is safe. You've donned your surgical mask and nitrile gloves and confirmed no environmental hazards. You're ready to approach.",
      feedbackIncorrect: "Always don PPE first - surgical mask and nitrile gloves - then visually scan the environment for safety hazards before approaching any patient.",
      hint: "What do you always do FIRST at every single scene before touching a patient?",
      isCritical: false,
      videoUrl: "/videos/s2-step1-ppe-scene-safety.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 2,
      phase: "General Impression",
      prompt: "You see 28-year-old Marcus on the gray sofa in a severe tripod position - leaning forward, hands braced on his knees. His skin is pale and sweaty with visible nasal flaring and retractions. What is your general impression and what do you do?",
      patientState: "One adult male patient in severe respiratory distress. Marcus is pale with a grayish tint, diaphoretic with sweat visible on his forehead. Pronounced nasal flaring and intercostal retractions with every breath. Girlfriend Jenna hovers anxiously nearby.",
      vitalSigns: null,
      correctActions: ["General impression: adult male in severe respiratory distress, life threat identified. Immediately request ALS backup via radio"],
      incorrectActions: [
        "No additional resources needed, BLS can handle this alone",
        "Request police for crowd control",
        "Wait and observe before deciding on resources",
      ],
      feedbackCorrect: "Excellent! You correctly identified one patient - an adult male in severe respiratory distress - and immediately requested ALS backup. Paramedics can administer nebulized bronchodilators and provide advanced airway management if needed.",
      feedbackIncorrect: "A patient with severe respiratory distress, tripod positioning, nasal flaring, and retractions needs ALS resources immediately. Paramedics can administer nebulized bronchodilators and provide advanced interventions.",
      hint: "How many patients? What is your general impression of severity? Do you need advanced life support?",
      isCritical: true,
      videoUrl: "/videos/s2-step2-general-impression.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 3,
      phase: "History",
      prompt: "You approach Marcus and kneel to his eye level. You ask Jenna: 'Did he fall or get hurt?' She shakes her head: 'No, it's his asthma - he was running outside.' You say 'Marcus, look at me' - he makes eye contact but can barely speak, managing only a slight nod. What do you determine?",
      patientState: "Marcus is alert - he tracks movement with wide, anxious eyes and makes eye contact. He nods slightly but is unable to speak full sentences due to severe breathlessness. No signs of trauma.",
      vitalSigns: null,
      correctActions: ["Nature of Illness is shortness of breath (asthma). No mechanism of injury, no spinal precautions needed. Patient is Alert on AVPU"],
      incorrectActions: [
        "Apply spinal precautions since the cause is unclear",
        "Patient is Verbal on AVPU since he nodded",
        "Patient is Unresponsive since he cannot speak",
      ],
      feedbackCorrect: "Correct! The NOI is shortness of breath from known asthma. No trauma means no spinal precautions needed. The patient is Alert (A on AVPU) - he makes eye contact and responds, even though he can barely verbalize.",
      feedbackIncorrect: "The girlfriend confirms this is an asthma attack, not trauma - no spinal precautions needed. Marcus is Alert (A on AVPU) because he makes eye contact, tracks movement, and nods. Being unable to speak due to respiratory distress is not the same as being unresponsive.",
      hint: "Was there a mechanism of injury? Is the patient Alert, Verbal, Pain, or Unresponsive?",
      isCritical: false,
      videoUrl: "/videos/s2-step3-moi-avpu.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 4,
      phase: "Primary Assessment",
      prompt: "You assess the airway and breathing. You listen with your stethoscope and hear significant high-pitched wheezing in all lung fields. You observe deep intercostal and substernal retractions with dramatic nasal flaring. What are your findings?",
      patientState: "Airway is patent - no obstruction, secretions, or foreign body. Breathing is severely labored with high-pitched expiratory wheezing, pronounced retractions visible at the neckline and below the sternum, and dramatic nasal flaring with every breath.",
      vitalSigns: { hr: 128, rr: 32, spo2: 86, skinColor: "Pale with grayish tint", skinTemp: "Cool", skinMoisture: "Diaphoretic" },
      correctActions: ["Airway is patent but breathing is severely labored with significant wheezing, retractions, and severe work of breathing. This is a critical respiratory emergency"],
      incorrectActions: [
        "Airway is obstructed, perform abdominal thrusts",
        "Breathing is adequate, continue assessment without intervention",
        "Insert an OPA to maintain the airway",
      ],
      feedbackCorrect: "Correct! The airway is patent - there's no obstruction. But the breathing assessment reveals severe distress: high-pitched wheezing, retractions, and severe work of breathing requiring immediate intervention.",
      feedbackIncorrect: "The airway is open (patent) - wheezing is in the lungs, not the airway. But the severe wheezing, retractions, and work of breathing indicate a critical respiratory emergency that needs immediate treatment.",
      hint: "Is the airway open? What do the wheezing, retractions, and nasal flaring tell you about the breathing?",
      isCritical: true,
      videoUrl: "/videos/s2-step4-airway-breathing.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 5,
      phase: "Primary Assessment",
      prompt: "Jenna hands you Marcus's prescribed metered-dose inhaler (MDI) with a spacer device. SpO2 is 86%. What is your first breathing intervention?",
      patientState: "Jenna produces Marcus's prescribed albuterol inhaler with a spacer attachment. Marcus remains in tripod position with severe wheezing and retractions.",
      vitalSigns: { hr: 128, rr: 32, spo2: 86, skinColor: "Pale", skinTemp: "Cool", skinMoisture: "Diaphoretic" },
      correctActions: ["Assist with the prescribed inhaler: shake the MDI, attach to spacer, place mouthpiece between patient's lips with a seal, and administer one puff"],
      incorrectActions: [
        "Refuse the inhaler and wait for ALS to administer medication",
        "Have the patient inhale the MDI directly without the spacer",
        "Administer the entire inhaler at once",
      ],
      feedbackCorrect: "Excellent! EMTs can assist with a patient's prescribed MDI. Shaking the inhaler, using the spacer for better delivery, ensuring a good seal, and administering one puff at a time is the correct technique.",
      feedbackIncorrect: "EMTs are authorized to assist with a patient's own prescribed inhaler. The spacer device improves medication delivery to the lungs. Shake the MDI, attach to spacer, seal the mouthpiece, and deliver one puff.",
      hint: "Can EMTs assist with a patient's prescribed inhaler? How should it be administered with a spacer?",
      isCritical: true,
      videoUrl: "/videos/s2-step5-inhaler.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 6,
      phase: "Primary Assessment",
      prompt: "After the inhaler, SpO2 remains at 86%. You need to provide supplemental oxygen. What device and flow rate do you use?",
      patientState: "The inhaler has been administered but the patient remains in significant distress. SpO2 is still critically low at 86%. Wheezing continues.",
      vitalSigns: { hr: 130, rr: 30, spo2: 86, skinColor: "Pale", skinTemp: "Cool", skinMoisture: "Diaphoretic" },
      correctActions: ["Apply high-flow oxygen via non-rebreather mask at 15 liters per minute - the SpO2 of 86% requires maximum oxygen delivery"],
      incorrectActions: [
        "Nasal cannula at 2 LPM is sufficient",
        "No oxygen needed since the inhaler was given",
        "Blow-by oxygen held near the face at 6 LPM",
      ],
      feedbackCorrect: "Correct! With an SpO2 of 86%, high-flow O2 via non-rebreather at 15 LPM is required. You retrieve the NRB from your bag, connect it to the oxygen cylinder, turn the flow high to inflate the reservoir bag, then apply the mask to the patient's face.",
      feedbackIncorrect: "An SpO2 of 86% is critically low and requires maximum oxygen delivery. A non-rebreather mask at 15 LPM provides the highest concentration of oxygen at the BLS level.",
      hint: "What oxygen delivery device provides the highest concentration at the BLS level? What flow rate?",
      isCritical: true,
      videoUrl: "/videos/s2-step6-oxygen.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 7,
      phase: "Primary Assessment",
      prompt: "You assess circulation. You feel Marcus's forehead - it's cool and sweaty. You check his radial pulse - it's rapid and thready at 132 bpm. Capillary refill is 4 seconds. No external bleeding. What do these findings indicate?",
      patientState: "Skin is pale, cool, and diaphoretic with visible sweat on forehead and upper lip. Radial pulse is rapid and weak (thready). Capillary refill delayed at 4 seconds. No gross bleeding anywhere.",
      vitalSigns: { hr: 132, rr: 30, spo2: 87, skinColor: "Pale", skinTemp: "Cool", skinMoisture: "Diaphoretic" },
      correctActions: ["Skin is pale, cool, and diaphoretic. Pulse is rapid and thready. Capillary refill is delayed. These findings indicate poor perfusion consistent with compensated shock"],
      incorrectActions: [
        "Circulation is normal for someone who was exercising",
        "Apply a tourniquet for the poor perfusion",
        "These are normal vital signs for a healthy adult",
      ],
      feedbackCorrect: "Correct! Pale, cool, diaphoretic skin with a rapid thready pulse and delayed capillary refill are classic signs of poor perfusion. Combined with the respiratory distress, this indicates a critically ill patient.",
      feedbackIncorrect: "Pale, cool, diaphoretic skin with tachycardia and delayed capillary refill are NOT normal. These are signs of poor perfusion/compensated shock in a critically ill patient.",
      hint: "What do pale, cool, sweaty skin with a fast weak pulse and slow capillary refill tell you about perfusion?",
      isCritical: true,
      videoUrl: "/videos/s2-step7-circulation.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 8,
      phase: "Transport Decision",
      prompt: "Based on your assessment - severe respiratory distress, SpO2 of 87%, poor perfusion, and difficulty speaking - how do you prioritize this patient and what is your transport decision?",
      patientState: "Marcus remains in severe distress with the oxygen mask in place. He is becoming more fatigued and less responsive to his surroundings. Jenna looks at you with fear in her eyes.",
      vitalSigns: { hr: 132, rr: 30, spo2: 87, skinColor: "Pale", skinTemp: "Cool", skinMoisture: "Diaphoretic" },
      correctActions: ["This is a HIGH priority patient. Move immediately to the ambulance. Gather SAMPLE/OPQRST history en route - do NOT delay on scene for an unstable patient"],
      incorrectActions: [
        "Stay on scene to complete a full SAMPLE history before moving",
        "Low priority, the oxygen will fix the problem",
        "Wait for ALS to arrive before transporting",
      ],
      feedbackCorrect: "Excellent decision! This is a high-priority patient who needs immediate transport. You'll gather the SAMPLE and OPQRST history en route to the hospital since the patient is unstable and should not be delayed on scene.",
      feedbackIncorrect: "A patient with severe respiratory distress, poor perfusion, and declining mental status is HIGH priority. Never delay transport of an unstable patient - gather history en route.",
      hint: "Should you delay transport to complete history-taking with a critically ill, unstable patient?",
      isCritical: true,
      videoUrl: "/videos/s2-step8-prioritize.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 9,
      phase: "Transport",
      prompt: "You bring the stretcher next to the sofa. How should Marcus be positioned on the stretcher for transport?",
      patientState: "The wheeled ambulance stretcher is positioned next to the sofa. Marcus needs to be moved from the couch to the stretcher while maintaining oxygen delivery.",
      vitalSigns: { hr: 130, rr: 28, spo2: 88, skinColor: "Pale", skinTemp: "Cool", skinMoisture: "Diaphoretic" },
      correctActions: ["Position the patient sitting fully upright (High Fowler's position) on the stretcher - NOT lying flat. Maintain oxygen mask. Secure safety straps across chest and legs"],
      incorrectActions: [
        "Lay the patient flat on his back on the stretcher",
        "Place the patient in the recovery position on his side",
        "Let the patient sit however he wants without securing straps",
      ],
      feedbackCorrect: "Perfect! A patient in severe respiratory distress must remain sitting upright (High Fowler's position) to maximize breathing ability. Lying flat would worsen the distress. Oxygen stays on, and safety straps are secured.",
      feedbackIncorrect: "NEVER lay a patient in severe respiratory distress flat - it makes breathing much harder. High Fowler's (sitting fully upright) is required. The oxygen mask must stay on and safety straps must be secured.",
      hint: "What position helps a patient in severe respiratory distress breathe most effectively?",
      isCritical: true,
      videoUrl: "/videos/s2-step9-stretcher.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario2.id,
      stepOrder: 10,
      phase: "Transport",
      prompt: "You're in the ambulance with Marcus secured upright on the stretcher and Jenna seated nearby. What do you do during transport?",
      patientState: "Inside the ambulance with bright overhead LED lighting. Marcus is secured on the stretcher in High Fowler's position wearing the oxygen mask. Jenna is seated on the bench.",
      vitalSigns: { hr: 124, rr: 26, spo2: 90, skinColor: "Pale", skinTemp: "Cool", skinMoisture: "Less diaphoretic" },
      correctActions: ["Reassess vital signs continuously (attach pulse oximeter), monitor airway and breathing, and begin gathering SAMPLE history from the girlfriend en route"],
      incorrectActions: [
        "No further assessment needed, just drive to the hospital",
        "Remove the oxygen mask since SpO2 improved slightly",
        "Wait until arrival at the hospital to reassess",
      ],
      feedbackCorrect: "Correct! During transport, you continuously reassess vitals, monitor the airway and breathing, attach monitoring equipment like a pulse oximeter, and begin gathering the SAMPLE history from Jenna. You ask: 'Is he allergic to any medications?'",
      feedbackIncorrect: "Critical patients require continuous reassessment during transport. Attach a pulse oximeter, monitor vital signs, keep the oxygen flowing, and gather the SAMPLE history from Jenna en route.",
      hint: "What should you be doing in the ambulance with a critical patient? Can you gather history now?",
      isCritical: false,
      videoUrl: "/videos/s2-step10-transport.mp4",
    }),
  ]);

  const scenario3 = await storage.createScenario({
    title: "Respiratory Failure - Elderly Patient",
    description: "A 72-year-old male is found unresponsive in bed with snoring respirations, extremely low oxygen saturation, and weak pulse. Requires immediate airway management.",
    patientSummary: "72M, unresponsive, snoring respirations, RR 4, SpO2 70%, HR 52, cyanotic.",
    difficulty: "Advanced",
    category: "Medical",
    certLevel: "EMT",
    imageUrl: "/images/scenario-elderly.png",
    estimatedMinutes: 10,
    tags: ["respiratory failure", "BVM", "airway management", "geriatric"],
    departureVideoUrl: "/videos/s3-departure.mp4",
  });

  await Promise.all([
    storage.createScenarioStep({
      scenarioId: scenario3.id,
      stepOrder: 1,
      phase: "Scene Safety",
      prompt: "You respond to a residence for an unresponsive male. What is your first action upon arrival?",
      patientState: "Family member meets you at the door, very distressed. 'He won't wake up! Please hurry!'",
      vitalSigns: null,
      correctActions: ["Don BSI/PPE including gloves, mask, and eye protection, then confirm scene safety"],
      incorrectActions: [
        "Rush to the patient's bedside immediately",
        "Ask the family what medications he takes",
        "Call for helicopter transport",
      ],
      feedbackCorrect: "Correct! Even in critical situations, BSI/PPE comes first. Eye protection is especially important when managing airways.",
      feedbackIncorrect: "Always don PPE first, including eye protection for airway management cases. Scene safety is non-negotiable.",
      hint: "What PPE is especially important when you may need to manage an airway?",
      isCritical: false,
      videoUrl: "/videos/s3-step1-arrive-house-night.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario3.id,
      stepOrder: 2,
      phase: "Scene Size-Up",
      prompt: "Scene is safe. One patient in bed, unresponsive. What resources do you request?",
      patientState: "72-year-old male lying in bed, cyanotic, snoring respirations audible from the doorway.",
      vitalSigns: null,
      correctActions: ["Call for ALS immediately - unresponsive patient with respiratory failure requires advanced airway management"],
      incorrectActions: [
        "No additional resources needed",
        "Call for police assistance",
        "Request fire department only",
      ],
      feedbackCorrect: "Excellent! An unresponsive patient with respiratory failure absolutely needs ALS for advanced airway management and medications.",
      feedbackIncorrect: "An unresponsive patient with signs of respiratory failure needs ALS. Paramedics can provide advanced airway management and medications.",
      hint: "Can BLS alone manage an unresponsive patient in respiratory failure?",
      isCritical: false,
      videoUrl: "/videos/s3-step2-enter-bedroom.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario3.id,
      stepOrder: 3,
      phase: "General Impression",
      prompt: "The patient is cyanotic with snoring respirations, groans only to painful stimuli. How do you assess his level of consciousness?",
      patientState: "Patient is lying supine, cyanotic lips and fingertips. Snoring with each breath. Only groans when you apply a sternal rub.",
      vitalSigns: { hr: 52, rr: 4, spo2: 70, bp: "92/58", skinColor: "Cyanotic", skinTemp: "Cool", skinMoisture: "Clammy" },
      correctActions: ["Patient responds to Pain only (P on AVPU). This is a critical, life-threatening emergency"],
      incorrectActions: [
        "Patient is Alert (A on AVPU)",
        "Patient is Unresponsive (U on AVPU)",
        "Patient responds to Verbal stimuli (V on AVPU)",
      ],
      feedbackCorrect: "Correct! Groaning to painful stimuli = Painful response (P) on AVPU. With an SpO2 of 70%, this is immediately life-threatening.",
      feedbackIncorrect: "The patient only responds to pain (groaning with sternal rub). He is not alert, doesn't respond to voice, and is not completely unresponsive. He is P on AVPU.",
      hint: "He doesn't respond to your voice but groans when you apply pain. Where does that fall on AVPU?",
      isCritical: true,
      videoUrl: "/videos/s3-step3-approach-bed.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario3.id,
      stepOrder: 4,
      phase: "Primary Assessment",
      prompt: "The patient has snoring respirations. How do you manage the airway?",
      patientState: "Loud snoring with each breath. The tongue appears to be partially obstructing the airway. RR is 4 breaths per minute.",
      vitalSigns: { hr: 52, rr: 4, spo2: 70, bp: "92/58", skinColor: "Cyanotic", skinTemp: "Cool", skinMoisture: "Clammy" },
      correctActions: ["Open airway with head-tilt chin-lift and insert an OPA (oropharyngeal airway) to maintain patency"],
      incorrectActions: [
        "The airway is fine, snoring is normal in sleep",
        "Place the patient on their stomach",
        "Insert a nasal cannula",
      ],
      feedbackCorrect: "Excellent! Snoring respirations indicate a partial airway obstruction. Head-tilt chin-lift opens it, and an OPA maintains it in an unresponsive patient.",
      feedbackIncorrect: "Snoring respirations mean the airway is partially obstructed, likely by the tongue. You must open it with a head-tilt chin-lift and maintain with an OPA.",
      hint: "What causes snoring respirations? How do you fix it and keep it open?",
      isCritical: true,
      videoUrl: "/videos/s3-step4-open-airway.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario3.id,
      stepOrder: 5,
      phase: "Primary Assessment",
      prompt: "Airway is now open with OPA in place. RR is 4, SpO2 is 70%. The breathing is clearly inadequate. What is your intervention?",
      patientState: "With OPA in place, snoring has stopped. However, respirations remain at 4/min and very shallow. SpO2 remains critically low at 70%.",
      vitalSigns: { hr: 52, rr: 4, spo2: 70, bp: "92/58", skinColor: "Cyanotic", skinTemp: "Cool", skinMoisture: "Clammy" },
      correctActions: ["Begin assisted ventilations with BVM connected to high-flow oxygen at 15 LPM - respirations are inadequate"],
      incorrectActions: [
        "Apply non-rebreather mask at 15 LPM",
        "Apply nasal cannula at 6 LPM",
        "Wait for ALS before providing ventilatory support",
      ],
      feedbackCorrect: "Perfect! A respiratory rate of 4 is grossly inadequate. BVM ventilations with high-flow O2 is the only appropriate intervention here.",
      feedbackIncorrect: "A respiratory rate of 4 means the patient is barely breathing. Passive oxygen (NRB, nasal cannula) is not enough. You must actively ventilate with a BVM.",
      hint: "Is a respiratory rate of 4 adequate? Can passive oxygen delivery fix an SpO2 of 70% at this rate?",
      isCritical: true,
      videoUrl: "/videos/s3-step5-bvm-ventilate.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario3.id,
      stepOrder: 6,
      phase: "Reassessment",
      prompt: "After 2 minutes of BVM ventilations with O2, you reassess. SpO2 has risen to 86%, HR to 66. Skin color improving slightly. Patient begins to move arms. What do you do?",
      patientState: "With continued BVM ventilations, the patient's color is slowly improving. He begins moving his arms slightly but remains non-verbal.",
      vitalSigns: { hr: 66, rr: 8, spo2: 86, bp: "98/62", skinColor: "Less cyanotic", skinTemp: "Cool", skinMoisture: "Clammy" },
      correctActions: ["Continue BVM ventilations - SpO2 is improving but still below normal. Monitor for increased consciousness and prepare for potential OPA removal if gag reflex returns"],
      incorrectActions: [
        "Stop BVM ventilations since SpO2 improved",
        "Remove the OPA since the patient is moving",
        "Downgrade to nasal cannula since he's getting better",
      ],
      feedbackCorrect: "Correct! The improvement is encouraging but SpO2 is still low. Continue BVM. Watch for gag reflex return as consciousness improves.",
      feedbackIncorrect: "An SpO2 of 86% is still dangerously low. Continue BVM ventilations. Don't remove the OPA unless the patient develops a gag reflex.",
      hint: "Is 86% a normal SpO2? Should you stop an intervention that's working just because there's some improvement?",
      isCritical: true,
      videoUrl: "/videos/s3-step6-reassess.mp4",
    }),
  ]);

  const scenario4 = await storage.createScenario({
    title: "Motor Vehicle Collision",
    description: "Respond to a two-vehicle collision on a suburban road. One patient is trapped with multiple injuries. Perform a systematic trauma assessment.",
    patientSummary: "35M, restrained driver, airbag deployed, complaining of chest and neck pain, possible entrapment.",
    difficulty: "Intermediate",
    category: "Trauma",
    certLevel: "EMT",
    imageUrl: "/images/scenario-assessment.png",
    estimatedMinutes: 12,
    tags: ["trauma", "MVC", "spinal", "extrication"],
    departureVideoUrl: "/videos/s4-departure.mp4",
  });

  await Promise.all([
    storage.createScenarioStep({
      scenarioId: scenario4.id,
      stepOrder: 1,
      phase: "Scene Safety",
      prompt: "You arrive at a two-vehicle collision on a suburban road. What are your first actions?",
      patientState: "Two vehicles with front-end damage on a two-lane road. Fluids leaking from one vehicle. Traffic passing slowly.",
      vitalSigns: null,
      correctActions: ["Don BSI/PPE, assess scene safety including traffic hazards, fluid leaks, and vehicle stability"],
      incorrectActions: [
        "Rush to the nearest vehicle to check patients",
        "Direct traffic yourself without PPE",
        "Begin extrication immediately",
      ],
      feedbackCorrect: "Correct! MVC scenes have multiple hazards: traffic, leaking fluids, unstable vehicles, broken glass. Scene safety is critical.",
      feedbackIncorrect: "MVC scenes are among the most dangerous. Assess for traffic hazards, leaking fluids, vehicle stability, and downed power lines before approaching.",
      hint: "What hazards are unique to motor vehicle collision scenes?",
      isCritical: false,
      videoUrl: "/videos/s4-step1-arrive-mvc.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario4.id,
      stepOrder: 2,
      phase: "Scene Size-Up",
      prompt: "Two vehicles, two potential patients. The second vehicle's occupant is ambulatory and appears uninjured. What resources do you need?",
      patientState: "Vehicle 1: driver pinned by dashboard, conscious, in pain. Vehicle 2: driver standing outside, appears uninjured.",
      vitalSigns: null,
      correctActions: ["Call for fire/rescue for extrication, request additional ambulance for second patient, consider ALS for the trapped patient"],
      incorrectActions: [
        "No additional resources needed",
        "Only request police for traffic control",
        "Tell the ambulatory patient to drive themselves to the hospital",
      ],
      feedbackCorrect: "Good thinking! Entrapped patients need fire/rescue. Every patient at an MVC needs evaluation, even if they appear uninjured.",
      feedbackIncorrect: "A trapped patient requires fire/rescue for extrication. You need additional resources, and the second patient must also be evaluated.",
      hint: "One patient is trapped. Can you extricate them? Does the other patient need evaluation?",
      isCritical: false,
      videoUrl: "/videos/s4-step2-approach-vehicles.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario4.id,
      stepOrder: 3,
      phase: "General Impression",
      prompt: "You reach the trapped driver. He is alert, restrained, airbag deployed. He complains of chest and neck pain. What's your immediate concern?",
      patientState: "35-year-old male, seatbelt on, airbag deployed. Steering wheel deformed. Complaints of neck and chest pain. Dashboard pressing on his legs.",
      vitalSigns: { hr: 108, rr: 22, spo2: 95, bp: "128/82" },
      correctActions: ["Manually stabilize the cervical spine - mechanism and symptoms suggest potential spinal injury"],
      incorrectActions: [
        "No spinal precautions needed since he's conscious",
        "Wait for extrication before any assessment",
        "Pull the patient from the vehicle immediately",
      ],
      feedbackCorrect: "Excellent! High-speed MVC with neck pain is a classic indication for spinal precautions. Manual c-spine stabilization should begin immediately.",
      feedbackIncorrect: "A high-speed MVC with neck pain requires immediate manual cervical spine stabilization. Never move a trauma patient without protecting the spine first.",
      hint: "What does neck pain after a high-speed collision tell you about spinal injury risk?",
      isCritical: true,
      videoUrl: "/videos/s4-step3-look-in-car.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario4.id,
      stepOrder: 4,
      phase: "Primary Assessment",
      prompt: "With c-spine stabilized, you assess the airway and breathing. The patient is speaking clearly, RR 22, SpO2 95%. He has tenderness over the left chest wall. What do you do?",
      patientState: "Patient speaking in full sentences. Left chest wall tender to palpation. Equal chest rise bilaterally. Breath sounds slightly diminished on the left.",
      vitalSigns: { hr: 108, rr: 22, spo2: 95, bp: "128/82", skinColor: "Pink", skinTemp: "Warm", skinMoisture: "Dry" },
      correctActions: ["Airway patent. Apply high-flow oxygen via non-rebreather at 15 LPM as a precaution for potential chest injury. Monitor for deterioration"],
      incorrectActions: [
        "No oxygen needed, SpO2 is 95%",
        "Begin CPR",
        "Insert an OPA",
      ],
      feedbackCorrect: "Correct! With possible chest wall injury and diminished breath sounds, prophylactic high-flow O2 is appropriate. Monitor closely for deterioration.",
      feedbackIncorrect: "Chest wall tenderness with diminished breath sounds suggests possible rib fractures or pneumothorax. High-flow O2 and close monitoring are essential.",
      hint: "What could cause diminished breath sounds on one side after blunt chest trauma?",
      isCritical: false,
      videoUrl: "/videos/s4-step4-stabilize-cspine.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario4.id,
      stepOrder: 5,
      phase: "Primary Assessment",
      prompt: "Circulation assessment: pulse 108, BP 128/82, skin warm and dry. No external hemorrhage visible. How do you prioritize this patient?",
      patientState: "Vitals relatively stable. Patient is alert and oriented. Still complaining of neck and chest pain. Remains trapped.",
      vitalSigns: { hr: 108, rr: 22, spo2: 95, bp: "128/82", skinColor: "Pink", skinTemp: "Warm", skinMoisture: "Dry" },
      correctActions: ["HIGH priority patient due to mechanism, entrapment, neck pain, and possible chest injury. Expedite extrication and transport"],
      incorrectActions: [
        "Low priority since vitals are stable",
        "Delayed priority, treat other patients first",
        "No priority needed, he can wait for extrication",
      ],
      feedbackCorrect: "Correct! Despite relatively stable vitals, the mechanism, entrapment, spinal concerns, and chest injury make this a high priority patient.",
      feedbackIncorrect: "Stable vitals don't mean low priority. The mechanism of injury, entrapment, neck pain, and possible chest injury all point to high priority.",
      hint: "Should you base priority only on current vitals, or also consider the mechanism and potential injuries?",
      isCritical: true,
      videoUrl: "/videos/s4-step5-assess-trapped.mp4",
    }),
  ]);

  const scenario5 = await storage.createScenario({
    title: "Cardiac Arrest - Witnessed",
    description: "A 58-year-old male collapses at a restaurant. Bystanders report he was eating, suddenly clutched his chest, and fell from his chair. He is now unresponsive.",
    patientSummary: "58M, witnessed collapse, unresponsive, no pulse, no breathing.",
    difficulty: "Advanced",
    category: "Medical",
    certLevel: "EMT",
    imageUrl: "/images/scenario-ambulance-interior.png",
    estimatedMinutes: 10,
    tags: ["cardiac arrest", "CPR", "AED", "BLS"],
    departureVideoUrl: "/videos/s5-departure.mp4",
  });

  await Promise.all([
    storage.createScenarioStep({
      scenarioId: scenario5.id,
      stepOrder: 1,
      phase: "Scene Safety",
      prompt: "You arrive at a restaurant for an unresponsive male. The scene is chaotic with bystanders surrounding the patient. What do you do first?",
      patientState: "A man is lying on the floor between tables. A crowd of 15-20 people surrounds him. One bystander is yelling for help.",
      vitalSigns: null,
      correctActions: ["Don BSI/PPE, confirm scene safety, and direct bystanders to clear space for you to work"],
      incorrectActions: [
        "Begin chest compressions immediately without PPE",
        "Ask bystanders what happened before approaching",
        "Call for police to manage the crowd first",
      ],
      feedbackCorrect: "Correct! PPE first, then clear the scene so you have space to work. In cardiac arrest, every second counts, but you still need PPE.",
      feedbackIncorrect: "Even in cardiac arrest, you need PPE. Get gloves on quickly, clear space, and then begin your assessment. It only takes seconds.",
      hint: "Can you do effective CPR in a crowd without PPE?",
      isCritical: false,
      videoUrl: "/videos/s5-step1-arrive-restaurant.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario5.id,
      stepOrder: 2,
      phase: "General Impression",
      prompt: "You reach the patient. He is supine, motionless, cyanotic. You shake his shoulders and shout - no response. What is your immediate assessment?",
      patientState: "58-year-old male, supine on restaurant floor. Not moving, not breathing, cyanotic. No response to shoulder tap and verbal stimulation.",
      vitalSigns: null,
      correctActions: ["Patient is Unresponsive (U on AVPU). Check for a pulse immediately - this may be cardiac arrest"],
      incorrectActions: [
        "Patient is responding to pain, continue talking to him",
        "Place the patient in the recovery position",
        "Begin a detailed head-to-toe exam",
      ],
      feedbackCorrect: "Correct! No response to stimulation = Unresponsive. Immediately check for pulse to confirm cardiac arrest.",
      feedbackIncorrect: "No response to shoulder tap or voice = Unresponsive (U on AVPU). With no breathing and cyanosis, immediately check for pulse.",
      hint: "No response to stimulation, not breathing, cyanotic. What life-threatening condition does this suggest?",
      isCritical: true,
      videoUrl: "/videos/s5-step2-enter-restaurant.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario5.id,
      stepOrder: 3,
      phase: "Primary Assessment",
      prompt: "You check the carotid pulse for 10 seconds - no pulse detected. No breathing observed. What do you do?",
      patientState: "No pulse. No respiratory effort. Patient is in cardiac arrest.",
      vitalSigns: null,
      correctActions: ["Begin high-quality CPR immediately: 30 compressions to 2 ventilations, apply AED as soon as available"],
      incorrectActions: [
        "Check for a pulse again to be sure",
        "Begin rescue breathing only",
        "Wait for ALS to arrive before starting CPR",
      ],
      feedbackCorrect: "Perfect! In cardiac arrest, begin CPR immediately. High-quality compressions (hard, fast, full recoil) with early defibrillation save lives.",
      feedbackIncorrect: "No pulse, no breathing = cardiac arrest. Begin CPR immediately. Every minute without CPR decreases survival by 7-10%.",
      hint: "What is the definitive treatment for cardiac arrest at the BLS level?",
      isCritical: true,
      videoUrl: "/videos/s5-step3-kneel-cpr.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario5.id,
      stepOrder: 4,
      phase: "Primary Assessment",
      prompt: "CPR is in progress. Your partner brings the AED. What are the correct steps?",
      patientState: "CPR in progress. Partner arrives with AED and additional equipment.",
      vitalSigns: null,
      correctActions: ["Power on AED, apply pads, stop CPR for analysis, follow AED prompts for shock if advised, then immediately resume CPR"],
      incorrectActions: [
        "Continue CPR and skip the AED",
        "Apply the AED pads but don't stop CPR for analysis",
        "Only apply the AED if the patient doesn't improve with CPR alone",
      ],
      feedbackCorrect: "Excellent! Early defibrillation is critical. Apply pads, allow analysis, deliver shock if advised, and immediately resume CPR after the shock.",
      feedbackIncorrect: "The AED is the most important intervention in cardiac arrest. Apply it as soon as available, follow its prompts, and resume CPR immediately after any shock.",
      hint: "In witnessed cardiac arrest, what single intervention has the greatest impact on survival?",
      isCritical: true,
      videoUrl: "/videos/s5-step4-apply-aed.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario5.id,
      stepOrder: 5,
      phase: "Reassessment",
      prompt: "AED delivered one shock. You've resumed CPR. After 2 minutes of CPR, what should you do?",
      patientState: "Two minutes since last AED analysis. CPR has been continuous with good quality compressions.",
      vitalSigns: null,
      correctActions: ["Pause CPR briefly for AED reanalysis. Check pulse. Switch compressors to prevent fatigue. Resume CPR immediately after analysis"],
      incorrectActions: [
        "Continue CPR without pausing for another 5 minutes",
        "Stop CPR and check for breathing only",
        "Remove AED pads since one shock was already delivered",
      ],
      feedbackCorrect: "Correct! Every 2 minutes: reanalyze with AED, check pulse, switch compressors. Compressor fatigue reduces CPR quality.",
      feedbackIncorrect: "The resuscitation cycle is 2 minutes of CPR, then pause for AED reanalysis, pulse check, and compressor switch. This ensures quality and checks for ROSC.",
      hint: "How often should you reanalyze, check pulse, and switch compressors during CPR?",
      isCritical: true,
      videoUrl: "/videos/s5-step5-continue-cpr.mp4",
    }),
  ]);
}

async function seedNursingScenario() {
  const scenario6 = await storage.createScenario({
    title: "Acute Stroke - CVA Recognition",
    description: "You are a student nurse precepting on a medical-surgical unit. During a routine assessment of a 67-year-old male patient admitted for hypertension and hyperlipidemia, you identify sudden neurological symptoms consistent with stroke. Activate the Code Stroke protocol and follow the patient through CT imaging, interventional radiology, and ICU transfer.",
    patientSummary: "67M 'Robert Hernandez', admitted for HTN and hyperlipidemia management. Develops acute onset facial droop, right-sided weakness, and slurred speech during morning assessment. Last known well 15 minutes prior.",
    difficulty: "Intermediate",
    category: "Neurological",
    certLevel: "RN",
    discipline: "Nursing",
    imageUrl: "/images/scenario-cva-stroke.png",
    estimatedMinutes: 25,
    tags: ["stroke", "CVA", "FAST", "Code Stroke", "neurological", "nursing", "med-surg", "thrombectomy", "SBAR"],
    departureVideoUrl: "/videos/s6-departure.mp4",
  });

  await Promise.all([
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 1,
      phase: "Patient Interaction",
      prompt: "You enter Room 412 on the medical-surgical unit with your preceptor. Mr. Hernandez is sitting in bed with cardiac monitoring and IV fluids running. What is your first action before beginning your assessment?",
      patientState: "Hospital med-surg room. 67-year-old male in hospital bed. Cardiac monitor showing normal sinus rhythm, IV saline infusing via pump. Wall oxygen and suction ports visible. Whiteboard reads: 'RN: Sarah, Student Nurse: Alex, Goal today: Blood pressure control.'",
      vitalSigns: null,
      correctActions: ["Perform hand hygiene and don appropriate PPE (gloves) before beginning the patient assessment"],
      incorrectActions: [
        "Begin taking vital signs immediately without hand hygiene",
        "Start reviewing the chart at the bedside computer",
        "Ask the preceptor what to do first",
      ],
      feedbackCorrect: "Correct! Hand hygiene and PPE are always performed before any patient interaction. This is a fundamental infection prevention practice.",
      feedbackIncorrect: "Hand hygiene and gloving must come before any patient contact. This is a core nursing standard for infection prevention.",
      hint: "What must you always do before touching a patient or their environment?",
      isCritical: false,
      videoUrl: "/videos/s6-step1-ppe.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 2,
      phase: "Patient Interaction",
      prompt: "You approach the bedside. How do you properly introduce yourself and verify the patient's identity?",
      patientState: "The patient looks at you as you approach. He appears slightly uncomfortable and holds his head. The hospital ID bracelet is on his left wrist.",
      vitalSigns: null,
      correctActions: ["Introduce yourself as the student nurse, then verify identity using two patient identifiers: ask for full name and date of birth, and cross-reference with the ID bracelet"],
      incorrectActions: [
        "Skip introductions and begin the physical assessment",
        "Just check the name on the whiteboard",
        "Ask the preceptor to confirm the patient's identity for you",
      ],
      feedbackCorrect: "Correct! You say: 'Hello Mr. Hernandez, I'm the student nurse working with your nurse today. Can you confirm your name and date of birth?' He replies with mild speech hesitation: 'My name.. is Robert.. Hernandez… February 18, 1958.'",
      feedbackIncorrect: "Patient identification requires two identifiers (name and DOB) confirmed directly with the patient and checked against the ID bracelet. This prevents medical errors.",
      hint: "How many patient identifiers are required? Where do you verify them?",
      isCritical: false,
      videoUrl: "/videos/s6-step2-identify.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 3,
      phase: "Patient Interaction",
      prompt: "During your general observation, you notice the patient appears slightly confused and is holding his head. He says: 'My head feels funny and I feel weak.' What do you recognize about these symptoms?",
      patientState: "The patient is holding his head, appears mildly confused, and reports feeling strange. His speech has a slight hesitation that was not present in his previous assessments documented in the chart.",
      vitalSigns: { hr: 88, rr: 18, bp: "168/94", spo2: 96 },
      correctActions: ["These symptoms — sudden headache, confusion, weakness, and speech changes — suggest a possible neurological emergency. This warrants immediate further assessment"],
      incorrectActions: [
        "This is likely just a headache from his hypertension, offer Tylenol",
        "He's probably just tired, let him rest and recheck later",
        "Document the complaint and continue with routine vitals",
      ],
      feedbackCorrect: "Excellent recognition! Sudden onset of headache, confusion, weakness, and speech changes are red flags for a neurological event. You correctly identify the need for immediate further assessment.",
      feedbackIncorrect: "Sudden onset headache, confusion, new weakness, and speech changes in a patient with hypertension are red flags for stroke. These symptoms require immediate neurological assessment, not routine documentation.",
      hint: "What neurological emergency presents with sudden headache, confusion, weakness, and speech changes?",
      isCritical: true,
      videoUrl: "/videos/s6-step3-observe.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 4,
      phase: "Assessment",
      prompt: "You suspect a possible neurological emergency. Which of the following symptoms should immediately raise concern for stroke?",
      patientState: "The patient continues to hold his head, his speech hesitation is becoming more noticeable, and he appears increasingly confused.",
      vitalSigns: { hr: 90, rr: 18, bp: "172/96", spo2: 95 },
      correctActions: ["Sudden facial droop is a hallmark stroke symptom and should immediately raise concern"],
      incorrectActions: [
        "A mild headache alone is the primary stroke indicator",
        "Slight fatigue is the most concerning symptom",
        "Mild nausea is the key stroke symptom",
      ],
      feedbackCorrect: "Correct! Sudden facial droop is one of the classic stroke warning signs. Along with arm weakness and speech changes, it forms the basis of the FAST stroke assessment.",
      feedbackIncorrect: "While headache, fatigue, and nausea can occur with stroke, sudden facial droop is a classic hallmark symptom. It is part of the FAST screening tool (Face, Arms, Speech, Time).",
      hint: "Think about the FAST acronym. What does the F stand for?",
      isCritical: true,
      videoUrl: "/videos/s6-step4-concern.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 5,
      phase: "Assessment",
      prompt: "You decide to perform a stroke screening. Which assessment tool is most appropriate for initial stroke screening at the med-surg bedside?",
      patientState: "The patient's symptoms are progressing. You need to quickly screen for stroke using a validated bedside tool.",
      vitalSigns: { hr: 92, rr: 20, bp: "174/98", spo2: 95 },
      correctActions: ["The FAST stroke assessment (Face, Arms, Speech, Time) is the most appropriate bedside screening tool for initial stroke recognition"],
      incorrectActions: [
        "The Glasgow Coma Scale is the best initial stroke screening tool",
        "The Braden Scale should be used to assess for stroke",
        "The Morse Fall Scale is the appropriate stroke screening tool",
      ],
      feedbackCorrect: "Correct! The FAST assessment (Face, Arms, Speech, Time) is designed specifically for rapid bedside stroke screening. It is quick, reliable, and can be performed by any nurse.",
      feedbackIncorrect: "The FAST stroke assessment is the gold standard for rapid bedside stroke screening. The Glasgow Coma Scale measures consciousness but is not specific to stroke. The Braden and Morse scales assess skin breakdown and fall risk respectively.",
      hint: "Which tool was specifically designed for rapid stroke screening using Face, Arms, Speech, and Time?",
      isCritical: true,
      videoUrl: "/videos/s6-step5-tool.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 6,
      phase: "FAST Assessment",
      prompt: "You begin the FAST assessment. You say: 'Mr. Hernandez, can you smile for me?' What do you observe?",
      patientState: "You stand at the bedside performing the FAST assessment. The preceptor watches closely, allowing you to lead. When asked to smile, the patient's face shows asymmetry.",
      vitalSigns: { hr: 94, rr: 20, bp: "176/98", spo2: 95 },
      correctActions: ["There is drooping on the right side of the patient's face. The right corner of his mouth does not rise symmetrically. This is a positive finding for facial droop"],
      incorrectActions: [
        "The patient's smile is symmetric and normal",
        "The patient cannot hear you, reposition and try again",
        "Facial assessment is inconclusive, skip to arms",
      ],
      feedbackCorrect: "Correct! You observe right-sided facial droop — the right corner of the mouth does not rise when the patient attempts to smile. This is a positive FAST finding.",
      feedbackIncorrect: "Look carefully at the patient's face when he smiles. The right side is drooping — the mouth corner does not rise equally. This asymmetry is a positive stroke screening finding.",
      hint: "Compare both sides of the face. Does one side move differently than the other?",
      isCritical: true,
      videoUrl: "/videos/s6-step6-face.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 7,
      phase: "FAST Assessment",
      prompt: "Next you assess arm strength: 'Please raise both of your arms and hold them out in front of you.' What do you observe?",
      patientState: "The patient raises both arms. His left arm stays elevated, but his right arm begins drifting downward despite visible effort to keep it raised.",
      vitalSigns: { hr: 94, rr: 20, bp: "178/100", spo2: 94 },
      correctActions: ["The patient's right arm is weak and drifting downward. This is a positive finding for arm drift, indicating right-sided motor weakness"],
      incorrectActions: [
        "Both arms are equal in strength",
        "The left arm is weak",
        "The patient is just tired from being in bed, this is normal",
      ],
      feedbackCorrect: "Correct! Right arm drift indicates right-sided motor weakness. Combined with the right facial droop, this suggests a left-hemisphere cerebrovascular event.",
      feedbackIncorrect: "The right arm drifts downward while the left stays up. This is NOT normal fatigue — it indicates unilateral motor weakness, a key stroke indicator.",
      hint: "Which arm is drifting? What does unilateral arm weakness suggest?",
      isCritical: true,
      videoUrl: "/videos/s6-step7-arms.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 8,
      phase: "FAST Assessment",
      prompt: "You assess speech: 'Please repeat this sentence: The sky is blue.' The patient attempts: 'The shky is blu…' with notably slurred speech. What is your finding?",
      patientState: "The patient struggles to repeat the phrase. His words are slurred and difficult to understand. He appears frustrated by his inability to speak clearly.",
      vitalSigns: { hr: 96, rr: 20, bp: "180/100", spo2: 94 },
      correctActions: ["The patient's speech is slurred (dysarthria). This is a positive finding for the Speech component of FAST"],
      incorrectActions: [
        "The patient's speech is clear and normal",
        "The patient is just nervous, give him time",
        "Speech issues are not relevant to stroke screening",
      ],
      feedbackCorrect: "Correct! The patient demonstrates dysarthria — slurred, garbled speech. This completes the FAST assessment: Face droop (positive), Arm drift (positive), Speech slurred (positive).",
      feedbackIncorrect: "The patient's speech is clearly slurred. He cannot properly articulate 'The sky is blue.' Dysarthria is a critical stroke indicator and the S in FAST.",
      hint: "Can the patient clearly repeat the phrase? What does slurred speech indicate in the FAST assessment?",
      isCritical: true,
      videoUrl: "/videos/s6-step8-speech.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 9,
      phase: "FAST Assessment",
      prompt: "Your FAST assessment shows: Facial droop (right side), Arm drift (right arm), Slurred speech. Which findings indicate a possible acute stroke?",
      patientState: "All three components of the FAST assessment are positive. The patient is becoming more anxious as his symptoms progress.",
      vitalSigns: { hr: 96, rr: 22, bp: "180/102", spo2: 94 },
      correctActions: ["All of the above — facial droop, arm weakness, AND slurred speech together indicate a possible acute stroke. All three FAST components are positive"],
      incorrectActions: [
        "Only facial droop alone indicates stroke",
        "Only arm weakness alone indicates stroke",
        "Only slurred speech alone indicates stroke",
      ],
      feedbackCorrect: "Correct! All three findings together strongly indicate an acute stroke. Any single positive FAST finding warrants concern, but all three together make the diagnosis highly likely. Time is now critical.",
      feedbackIncorrect: "While any single finding can indicate stroke, all three together — facial droop, arm weakness, and slurred speech — create an overwhelming clinical picture of acute stroke.",
      hint: "In FAST, do you need all three findings to be positive, or can any single finding indicate stroke?",
      isCritical: true,
      videoUrl: "/videos/s6-step9-recognize.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 10,
      phase: "FAST Assessment",
      prompt: "You have confirmed positive FAST findings. What is the most important immediate nursing action?",
      patientState: "The student nurse recognizes the findings suggest an acute stroke. The preceptor is watching, ready to support the student's next decision.",
      vitalSigns: { hr: 98, rr: 22, bp: "182/102", spo2: 93 },
      correctActions: ["Activate the hospital's stroke response protocol (Code Stroke) immediately — time is brain"],
      incorrectActions: [
        "Document the symptoms thoroughly in the chart first",
        "Wait for the physician to round and inform them then",
        "Administer pain medication for the patient's headache",
      ],
      feedbackCorrect: "Excellent! Activating the Code Stroke protocol is the correct immediate action. In stroke care, 'time is brain' — every minute of delay means more brain tissue lost. Documentation can happen after the protocol is activated.",
      feedbackIncorrect: "Documentation, waiting for rounds, and pain medication all delay the most critical action: activating Code Stroke. In acute stroke, every minute counts. Activate the protocol FIRST, then document.",
      hint: "In a time-sensitive neurological emergency, should documentation come before or after alerting the stroke team?",
      isCritical: true,
      videoUrl: "/videos/s6-step10-action.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 11,
      phase: "Code Stroke",
      prompt: "You report your findings to your preceptor: 'The patient has facial droop, arm weakness, and slurred speech.' She nods and instructs you to activate Code Stroke. You call it in. The overhead announcement sounds: 'Code Stroke, Room 412.' What critical information must you determine next?",
      patientState: "Code Stroke activated. Additional nurses arrive with the stroke response cart. Staff begin applying portable monitor leads, raising bed rails, and unlocking bed wheels for transport.",
      vitalSigns: { hr: 98, rr: 22, bp: "184/104", spo2: 93 },
      correctActions: ["Determine the time of symptom onset — 'When was the patient last seen normal?' The preceptor confirms he was speaking normally during morning rounds about 15 minutes ago. Last known well time: approximately 08:00 AM"],
      incorrectActions: [
        "Order a full metabolic panel immediately",
        "Begin administering blood pressure medication",
        "Start preparing discharge paperwork",
      ],
      feedbackCorrect: "Correct! The 'last known well' time is critical because it determines eligibility for time-sensitive treatments like tPA (alteplase). The patient was last seen normal approximately 15 minutes ago at 08:00 AM.",
      feedbackIncorrect: "The most critical information in acute stroke is the 'last known well' time — when the patient was last seen without symptoms. This determines eligibility for thrombolytic therapy.",
      hint: "What time-dependent information determines whether a stroke patient can receive clot-busting medication?",
      isCritical: true,
      videoUrl: "/videos/s6-step11-code-stroke.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 12,
      phase: "Code Stroke",
      prompt: "Why is identifying the time of symptom onset critical in acute stroke management?",
      patientState: "The stroke team is assembling. The last known well time has been established as approximately 08:00 AM — 15 minutes ago.",
      vitalSigns: { hr: 100, rr: 22, bp: "184/104", spo2: 93 },
      correctActions: ["The time of symptom onset determines eligibility for thrombolytic therapy (tPA/alteplase). tPA must be administered within 4.5 hours of symptom onset for ischemic stroke"],
      incorrectActions: [
        "It determines what diet the patient should receive",
        "It determines discharge planning timelines",
        "It determines the physical therapy schedule",
      ],
      feedbackCorrect: "Correct! tPA (alteplase) has a strict administration window — generally within 4.5 hours of symptom onset for ischemic stroke. Knowing the exact 'last known well' time is essential for treatment decisions.",
      feedbackIncorrect: "The time of onset is critical because thrombolytic therapy (tPA) has a strict time window. Missing this window means the patient cannot receive this life-saving clot-dissolving medication.",
      hint: "What stroke treatment has a strict time window measured from symptom onset?",
      isCritical: true,
      videoUrl: "/videos/s6-step12-onset-time.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 13,
      phase: "Code Stroke",
      prompt: "While awaiting the stroke team, you check the patient's blood glucose to rule out hypoglycemia. The reading is 110 mg/dL (normal). Your preceptor ensures IV access and cardiac monitoring. She tells you: 'I'm going to remain on the unit to care for our other patients. You can accompany the stroke team.' Which diagnostic test will most likely be performed first?",
      patientState: "Blood glucose is 110 mg/dL (normal). IV access confirmed. Cardiac monitoring in place. The patient is being prepared for transport to imaging.",
      vitalSigns: { hr: 100, rr: 22, bp: "186/104", spo2: 93 },
      correctActions: ["A head CT without contrast will be performed first. It is the priority diagnostic test to determine if the stroke is ischemic or hemorrhagic"],
      incorrectActions: [
        "A chest X-ray is the first priority test",
        "An abdominal ultrasound is needed first",
        "An MRI of the spine is the first diagnostic test",
      ],
      feedbackCorrect: "Correct! A non-contrast head CT is the first diagnostic test in acute stroke. It rapidly determines whether the stroke is ischemic (clot) or hemorrhagic (bleed), which dictates the treatment path.",
      feedbackIncorrect: "A non-contrast head CT is always the first imaging study in suspected stroke. It distinguishes ischemic from hemorrhagic stroke — a critical distinction that determines whether clot-dissolving medication can be given.",
      hint: "Which imaging test can rapidly differentiate between a clot-based stroke and a bleeding-based stroke?",
      isCritical: true,
      videoUrl: "/videos/s6-step13-glucose-prep.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 14,
      phase: "Transport to CT",
      prompt: "You accompany the stroke team as the patient is transported on the hospital bed through the hallway toward CT imaging. The patient appears anxious. What are your nursing priorities during transport?",
      patientState: "The patient is being transported on the hospital bed with a portable cardiac monitor attached. You pass other hospital rooms and take the elevator to the imaging floor. The patient grips the bedrails anxiously.",
      vitalSigns: { hr: 102, rr: 22, bp: "186/106", spo2: 93 },
      correctActions: ["Continue monitoring vital signs, maintain IV access, provide patient reassurance, and anticipate that a CT scan of the head will be performed to evaluate the stroke type"],
      incorrectActions: [
        "Disconnect the cardiac monitor for easier transport",
        "Tell the patient they are probably fine to avoid worrying them",
        "Stop at the nurses' station to update the chart before continuing to CT",
      ],
      feedbackCorrect: "Correct! During transport, maintain continuous monitoring, keep the IV running, reassure the patient, and anticipate the diagnostic testing. You tell him: 'We are taking you for imaging to evaluate your symptoms.'",
      feedbackIncorrect: "During critical patient transport, never disconnect monitoring, minimize delays, and provide honest reassurance. The patient's condition can change rapidly during an acute stroke.",
      hint: "What three things should you maintain during critical patient transport?",
      isCritical: false,
      videoUrl: "/videos/s6-step14-transport.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 15,
      phase: "Transport to CT",
      prompt: "You arrive at the CT suite. The radiology tech prepares the scanner. Why was checking blood glucose important in this suspected stroke patient?",
      patientState: "The CT scanning area has dimmed lighting. The large circular CT scanner is visible. The radiology technologist is at the control console. The patient will slide into the scanner on the motorized table.",
      vitalSigns: { hr: 102, rr: 22, bp: "188/106", spo2: 93 },
      correctActions: ["Hypoglycemia can mimic stroke symptoms. Checking blood glucose rules out a metabolic cause that could present identically to an acute stroke"],
      incorrectActions: [
        "Blood glucose determines stroke severity",
        "Blood glucose determines CT scan eligibility",
        "Blood glucose predicts recovery time",
      ],
      feedbackCorrect: "Correct! Hypoglycemia can cause confusion, weakness, slurred speech, and focal neurological deficits that closely mimic stroke. Ruling it out ensures you're treating the correct condition.",
      feedbackIncorrect: "Hypoglycemia is a 'stroke mimic' — it can cause identical symptoms including confusion, weakness, and speech changes. A normal blood glucose helps confirm the symptoms are truly neurological in origin.",
      hint: "What common metabolic condition can present with confusion, weakness, and slurred speech similar to stroke?",
      isCritical: false,
      videoUrl: "/videos/s6-step15-ct-suite.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 16,
      phase: "CT Results",
      prompt: "The CT scan is complete. If this patient meets eligibility criteria based on the CT findings and time of onset, which medication may be administered for ischemic stroke?",
      patientState: "The CT scan shows findings consistent with a large vessel occlusion in the left middle cerebral artery (MCA). No hemorrhage is identified. The stroke team reviews the images.",
      vitalSigns: { hr: 104, rr: 22, bp: "190/108", spo2: 92 },
      correctActions: ["Alteplase (tPA) may be administered if the patient meets eligibility criteria — it is the thrombolytic medication used to dissolve clots in ischemic stroke within the treatment window"],
      incorrectActions: [
        "Insulin should be administered",
        "Morphine is the appropriate medication",
        "A heparin bolus is the first-line treatment",
      ],
      feedbackCorrect: "Correct! Alteplase (tPA) is the thrombolytic medication for eligible ischemic stroke patients. However, due to the suspected large vessel occlusion, the stroke team determines the patient is also a candidate for mechanical thrombectomy.",
      feedbackIncorrect: "Alteplase (tPA) is the FDA-approved thrombolytic for acute ischemic stroke. It dissolves clots. Insulin, morphine, and heparin boluses are not first-line acute stroke treatments.",
      hint: "What class of medication dissolves blood clots? What is the generic name of the most common one used in stroke?",
      isCritical: true,
      videoUrl: "/videos/s6-step16-ct-results.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 17,
      phase: "Interventional Radiology",
      prompt: "The CT shows a large vessel occlusion in the middle cerebral artery. The patient is moved to Interventional Radiology for a procedure. What is the purpose of mechanical thrombectomy?",
      patientState: "The IR suite has bright overhead surgical lights. Staff wear lead aprons. A sterile instrument table is prepared. Large angiography monitors display cerebral blood vessels. The IR team prepares for the procedure.",
      vitalSigns: { hr: 104, rr: 24, bp: "190/108", spo2: 92 },
      correctActions: ["Mechanical thrombectomy physically removes a large blood clot from a cerebral artery using a catheter-based device. It is used for large vessel occlusions that may not respond adequately to tPA alone"],
      incorrectActions: [
        "Mechanical thrombectomy dissolves clots with medication",
        "Mechanical thrombectomy repairs damaged brain tissue",
        "Mechanical thrombectomy prevents infection",
      ],
      feedbackCorrect: "Correct! Mechanical thrombectomy uses a catheter inserted through the femoral artery to physically retrieve the clot from the cerebral artery. After the procedure, the patient is positioned flat with the affected leg straight following femoral artery access.",
      feedbackIncorrect: "Mechanical thrombectomy is a physical clot removal procedure, not a medication. A catheter device is threaded to the brain's arteries to mechanically extract the clot that is blocking blood flow.",
      hint: "Does 'mechanical' removal involve medication or a physical device?",
      isCritical: true,
      videoUrl: "/videos/s6-step17-ir.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 18,
      phase: "ICU Transfer",
      prompt: "After the IR procedure, the patient is transferred to the Neuro ICU. You participate in the SBAR handoff to the ICU nurse. Which nursing priority is most important post-stroke intervention in the ICU?",
      patientState: "The Neuro ICU has continuous arterial blood pressure waveforms, neuro monitoring equipment. The ICU nurse performs a pupil check with a penlight. The patient is positioned with head of bed less than 30 degrees post-procedure.",
      vitalSigns: { hr: 88, rr: 18, bp: "158/88", spo2: 96 },
      correctActions: ["Frequent neurological assessments are the most important post-stroke nursing priority. Serial neuro checks detect any changes in condition, re-occlusion, or hemorrhagic conversion early"],
      incorrectActions: [
        "Daily weight monitoring is the top priority",
        "Routine ambulation should begin immediately",
        "Dietary teaching is the most important priority",
      ],
      feedbackCorrect: "Correct! Frequent neurological assessments (often every 15-30 minutes initially) are the cornerstone of post-stroke ICU care. They detect deterioration, re-occlusion, or hemorrhagic conversion early when intervention is still possible.",
      feedbackIncorrect: "After a stroke intervention, the brain remains at risk for re-occlusion or hemorrhagic conversion. Frequent neurological assessments catch these life-threatening changes early. Weight monitoring, ambulation, and dietary teaching are important but not the immediate priority.",
      hint: "What is the biggest ongoing risk after stroke intervention that requires close monitoring?",
      isCritical: true,
      videoUrl: "/videos/s6-step18-icu.mp4",
    }),
    storage.createScenarioStep({
      scenarioId: scenario6.id,
      stepOrder: 19,
      phase: "Debrief",
      prompt: "You return to the med-surg unit with your preceptor. She debriefs the event with you: 'You identified stroke symptoms quickly during your assessment.' What is the most important nursing takeaway from this scenario?",
      patientState: "You and your preceptor walk back through the hospital hallway toward the med-surg nurses' station. The preceptor takes this opportunity to reinforce the key learning points.",
      vitalSigns: null,
      correctActions: ["Stroke treatment depends on rapid recognition and escalation of care. Early detection and immediate activation of the stroke protocol ensures patients receive time-sensitive treatment"],
      incorrectActions: [
        "Stroke symptoms resolve without treatment so timing doesn't matter",
        "Only physicians can identify strokes, nurses should not screen",
        "Neurological exams are unnecessary for med-surg patients",
      ],
      feedbackCorrect: "Excellent! Rapid recognition and escalation are critical in stroke care. Your quick identification of FAST symptoms and immediate activation of Code Stroke helped ensure this patient received time-sensitive treatment. Every minute counts — 'time is brain.'",
      feedbackIncorrect: "Stroke is a time-critical emergency. Nurses play a vital role in early recognition and escalation. Without rapid identification and protocol activation, patients miss the treatment window. Neurological assessments are essential on every unit.",
      hint: "What made the difference in this patient's outcome — the speed of recognition and escalation, or waiting for someone else to notice?",
      isCritical: false,
      videoUrl: "/videos/s6-step19-debrief.mp4",
    }),
  ]);
}
